### ISSUE TITLE
Add repository about section + docs link

### ISSUE THREAD

**Issue by Cooper-Kunz** [hiero-ledger/hiero-docs#1]
When visiting https://github.com/hashgraph/hedera-docs the repository "about" section is blank, as well as the link.

![Screen Shot 2020-07-07 at 1 37 48 PM](https://user-images.githubusercontent.com/11776938/86840122-37dadf00-c057-11ea-9c81-0ec65d2e89b3.png)

If we could update this to include a 1 sentence description of the repo, and link to https://docs.hedera.com - that'd be great!

**Comment by SimiHunjan** [comment]
Updated
