### ISSUE TITLE
<ADD IN EXAMPLE> stand-in blurb in getting started > create an account 

### ISSUE THREAD

**Issue by mowliv** [hiero-ledger/hiero-docs#101]
### Description

I see in https://docs.hedera.com/guides/getting-started/create-an-account there is the text "<ADD IN EXAMPLE>" at one spot. I'm assuming someone intended this as a reminder to add in some missing content...

Nice job with the getting started tutorial BTW. 

 

### Steps to reproduce

Read the page. 

### Hedera network

other

### Version

v1

### Operating system

macOS

**Comment by SimiHunjan** [comment]
Hi @mowliv ! Thank you for flagging. I have removed this for now and greatly appreciate your feedback!
