### ISSUE TITLE
Adding info to avoid confusion on allowance limits

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#109]
### Problem

In the doc page for allowances (https://docs.hedera.com/guides/docs/sdks/cryptocurrency/approve-an-allowance), we have: 
"Each account is limited to 100 allowances."

This actually confused various users in the ecosystem and made them think that this limitation was similar to the initial token association limit we used to have. 

### Solution

It is the approver account (ie the current token owner) has the 100 approval limitation.
It's NOT a limitation of the account receiving the approvals (ie Marketplace account).

We should write:
"Each owner account is limited to granting 100 allowances."

**Comment by theekrystallee** [comment]
Resolved in [f461801](https://github.com/hashgraph/hedera-docs/commit/f461801a32a32b8192c2f89b74ef8291a6667c74)
