### ISSUE TITLE
Querying by transaction type NODESTAKEUPDATE throws error

### ISSUE THREAD

**Issue by amacwhirter** [hiero-ledger/hiero-docs#110]
### Description

In the swagger documentation, adding the `transactiontype` parameter `NODESTAKEUPDATE` throws a 400 error stating 
```
{
  "_status": {
    "messages": [
      {
        "message": "Invalid parameter: transactiontype"
      }
    ]
  }
}
```
### 

### Steps to reproduce

1. Open testnet swagger docs
2. Go to `transactions` endpoint
3. Select `NODESTAKEUPDATE` in `transactiontype` query dropdown
4. Execute

### Additional context

![Uploading Screen Shot 2022-07-19 at 6.23.25 PM.png…]()

### Hedera network

testnet

### Version

 v0.60.0

### Operating system

macOS

**Comment by SimiHunjan** [comment]
Tagging @steven-sheehy from the mirror node team

**Comment by steven-sheehy** [comment]
That enum list comes from the SDK and we didn't update to a version of the SDK that has NODESTAKEUPDATE until v0.61.0-rc1. That version is still in testing but will be rolled out to environments soon. Note that there are zero NODESTAKEUPDATE transactions in testnet and mainnet now anyway. They only currently exist in previewnet.

**Comment by amacwhirter** [comment]
Thank you for the update @steven-sheehy - looking forward to the release
