### ISSUE TITLE
Adding limits on the number of child txs a parent tx can have and example

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#111]
### Problem

Received feedback from a user about parent/child txs. 
- We should document the max number of child txs a parent can have
- We should add a doc example for parent/child txs

### Solution

For the first point:
_A parent tx supports up to 999 child transactions since platform reserves 1000 ns per user submitted transaction. The nonce is the nanosecond offset from the parent consensus timestamp. But I wouldn't rely on that relationship of timestamp offset to nonce since it might change. Always use the consensus timestamps and transaction IDs w/ nonce in the records._

For the second point:
The feature doesn't actually work, so we need this issue resolved: https://github.com/hashgraph/hedera-sdk-js/issues/1186

**Comment by SimiHunjan** [comment]
Add here https://docs.hedera.com/guides/core-concepts/transactions-and-queries#nested-transactions. Please reopen if I missed anything @ed-marquez
