### ISSUE TITLE
Include documentation about the account portal / hbar faucet in the Introduction page

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#134]
### Problem

The page https://docs.hedera.com/guides/getting-started/introduction points new Hedera developers to the Hedera portal to obtain a new testnet account.

### Solution

The Introduction page should mention that: 
`Hedera Testnet accounts created through the portal are replenished with 10,000 test hbar every 24 hours. Effectively, the Hedera Portal acts like an hbar faucet for the testnet.`

**Comment by SimiHunjan** [comment]
Added https://docs.hedera.com/guides/getting-started/introduction#create-hedera-portal-profile-faucet
