### ISSUE TITLE
methods of the Client class on the hedera docs need to be updated

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#147]
### Description

In https://docs.hedera.com/guides/docs/sdks/client:

`.setDefaultMaxQueryPayment()` should be `.setMaxQueryPayment()`

### Steps to reproduce

 https://docs.hedera.com/guides/docs/sdks/client

### Hedera network

other

### Version

v0.1

**Comment by SimiHunjan** [comment]
hey @ed-marquez `setMaxQueryPayment()` is supposed to be deprecated in favor of `setDefaultMaxQueryPayement()`

Java has this: https://github.com/hashgraph/hedera-sdk-java/blob/main/sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java#L1144

I have opened an issue here:

https://github.com/hashgraph/hedera-sdk-js/issues/1297

**Comment by theekrystallee** [comment]
Resolved in [ccaae4f](https://github.com/hashgraph/hedera-docs/commit/ccaae4f887e78e8d5c50def58b7c7925efa230e1)
