### ISSUE TITLE
remove unmaintained community SDKs

### ISSUE THREAD

**Issue by Cooper-Kunz** [hiero-ledger/hiero-docs#15]
@SimiHunjan could you follow up with LaunchBadge & see which of these (if any) should still be encouraged?

We can remove the iOS from Rejolut as that hasn't been worked on in some time.

![Screen Shot 2020-12-10 at 1 17 30 PM](https://user-images.githubusercontent.com/11776938/101818861-17252280-3aea-11eb-816f-0e7a5135cbb2.png)

cc @donaldthibeau to make sure he's okay with the changes

**Comment by SimiHunjan** [comment]
Thanks @Cooper-Kunz for raising the issue. The table has been consolidated to the .net SDK.
