### ISSUE TITLE
How to Deploy Smart Contracts on Hedera – Part 1: A Simple Getter and Setter Contract has broken links (404)

### ISSUE THREAD

**Issue by iron4548** [hiero-ledger/hiero-docs#150]
### Description

https://docs.hedera.com/guides/getting-started/try-examples/deploy-a-contract-using-the-hedera-token-service

HederaTokenService.sol
IHederaTokenService.sol
HederaResponseCode.sol

These links give a 404 and needs updating.

### Steps to reproduce

1) https://docs.hedera.com/guides/getting-started/try-examples/deploy-a-contract-using-the-hedera-token-service
2) Click on broken links

### Hedera network

other

### Version

NA

**Comment by SimiHunjan** [comment]
Thank you for issue! Links are now fixed.
