### ISSUE TITLE
Add HTS demos to docs

### ISSUE THREAD

**Issue by donaldthibeau** [hiero-ledger/hiero-docs#16]
https://github.com/hashgraph/hedera-hts-demo

**Comment by donaldthibeau** [comment]
Please add both the fungible token and non fungible token service demo.

**Comment by SimiHunjan** [comment]
Demos was already added to the demo section in docs here: https://docs.hedera.com/guides/resources/demo-applications

**Comment by SimiHunjan** [comment]
- [x] Fungible token demo added
- [x] Non fungible token demo added
- [x] Missing demos added cc: @gregscullard
