### ISSUE TITLE
Add additional documentation to help users running into INSUFFICIENT_TX_FEE when creating tokens

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#161]
### Problem

Many users have encountered `INSUFFICIENT_TX_FEE` when creating tokens (very common issue).

This error occurs due to the default value for the max transaction fee field (1 HBAR). Creating tokens is usually well above that limit.

Fix: Right after defining the Hedera client, adding: 
`client.setDefaultMaxTransactionFee(new Hbar(100));` 
fixes the issue.

**Question**: To avoid so many people running into this issue, should we consider increasing that limit by default? Should we instead include that line for all doc pages that show how to create tokens? Other alternatives in mind?

I'm aware that this client modification is documented here: https://docs.hedera.com/guides/docs/sdks/client#3.-additional-client-modifications - but it's not in the context of expensive, frequent transactions like creating tokens`

### Solution

RESPONSE @simi: Depending on price of hbar 1 hbar might be enough if the price is high. If the price is low then it might not be enough. What we did not want to do in the SDK is set a high limit default to where let’s say it was 5 hbar and hbar price went to 10 dollars then the user is authorizing up to $50 per transaction fee as the default. The user may not want to do that because maybe the most they are willing to pay for a transaction is $5 and if it is over that they would not want it to go through. I think for the samples where we create tokens we should call out what the default is and that if they get an error they should look at updating the default value.

```[tasklist]
### Tasks
```

**Comment by SimiHunjan** [comment]
Closed as completed https://docs.hedera.com/hedera/getting-started/environment-set-up
Max default transaction fee is 100 now
