### ISSUE TITLE
Add docs for configuring a mirror node to receive specific data

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#162]
### Problem

Create guides that explain how to:

- Store only the last 90 days of data or given time period
- Store data for a specific entity (accounts, topics, etc)

References:

- https://github.com/hashgraph/hedera-mirror-node/blob/main/docs/configuration.md#transaction-and-entity-filtering
- https://github.com/hashgraph/hedera-mirror-node/blob/main/docs/database.md#retention
- https://github.com/hashgraph/roadmap/issues/113

### Solution

Add to existing guides or create a new one.

**Comment by SimiHunjan** [comment]
@SimiHunjan to review

**Comment by theekrystallee** [comment]
Tutorial is live - https://docs.hedera.com/hedera/tutorials/more-tutorials/how-to-configure-a-mirror-node-and-query-specific-data
