### ISSUE TITLE
Add docs for HIP-632 Hedera Account Service (HAS) System Contract

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#177]
### Problem

PR: https://github.com/hashgraph/hedera-improvement-proposal/pull/632/files

New feature that will require documentation. 

### Solution

Add documentation

**Comment by theekrystallee** [comment]
Resolved in [087b4b1](https://github.com/hashgraph/hedera-docs/commit/087b4b13e97b4ebed13f1fc732cd2597d49b35eb)

**Comment by theekrystallee** [comment]
resolved in [4e048aa](https://github.com/hashgraph/hedera-docs/commit/4e048aa493ff83e18edf0ed90c012de27c31be43)
