### ISSUE TITLE
Add Go getting started section

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#18]

**Comment by ptxmac** [comment]
A small note to this, the https://hedera.com/get-started page actually mentions go already, perhaps that should be removed until the documentation exists.

![image](https://user-images.githubusercontent.com/56919/105182234-19d55780-5b2d-11eb-9d12-865511fbc347.png)

**Comment by SimiHunjan** [comment]
Thank you @ptxmac for the note! The section is now added to the documentation.
