### ISSUE TITLE
Add docs for HIP-584: Mirror EVM Archive Node

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#180]
### Problem

New Feature: HIP-584: Mirror EVM Archive Node

### Solution

Add docs for `/api/v1/contracts/call` rest API

**Comment by SimiHunjan** [comment]
- [x] https://github.com/hashgraph/hedera-mirror-node/issues/5584

**Comment by theekrystallee** [comment]
Docs for /api/v1/contracts/call have been added
