### ISSUE TITLE
Remove Azure proxies

### ISSUE THREAD

**Issue by dalvizu** [hiero-ledger/hiero-docs#194]
We've removed Azure proxies from the address book and from the SDKs and intend to turn these off in 2023.

These are still listed on:

https://docs.hedera.com/hedera/mainnet/mainnet-nodes

We should remove these:
* 13.82.40.153
* 137.116.36.18
* 104.43.194.202
* 13.64.151.232
* 23.102.74.34
* 23.96.185.18
* 23.97.237.125
* 65.52.68.254
* 23.97.247.27
* 51.140.102.228
* 13.77.158.252
* 40.114.107.85
* 40.89.139.247
* 13.69.120.73
* 40.114.92.39
* 51.140.43.81
* 13.77.151.212
* 20.199.89.153
* 52.231.157.50

cc @popowycz

**Comment by JeromeK13** [comment]
Issue can be close, PR merged into master
