### ISSUE TITLE
Signing requirements need to be updated for "Create a Smart Contract" to include the key of the autorenewal account if specified

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#209]
### Description
@theekrystallee 
See: https://docs.hedera.com/hedera/docs/sdks/smart-contracts/create-a-smart-contract
The signing requirements in that page need to be updated to include the key of the autorenewal account, if specified. 

### Steps to reproduce

Here's a code sample: 

```
export async function deployContractFcn(bytecode, params, gasLim, autorenewAcc, autorenewAccKey, client) {
	const contractCreateTx = new ContractCreateFlow()
		.setBytecode(bytecode)
		.setConstructorParameters(params)
		.setGas(gasLim)
		// .setAutoRenewPeriod(7776000) //  Default: 7776000 = 90days. [2,592,000 (30 days) to 8,000,001 (92.5 days)]
		.setAutoRenewAccountId(autorenewAcc);
	const contractCreateSign = await contractCreateTx.sign(autorenewAccKey);
	const contractCreateSubmit = await contractCreateSign.execute(client);
	const contractCreateRx = await contractCreateSubmit.getReceipt(client);
	const contractId = contractCreateRx.contractId;
	const contractAddress = contractId.toSolidityAddress();
	return [contractId, contractAddress];
}
```
If that function is executed without passing the `autorenewAccKey` variable, then the transaction results in `INVALID_SIGNATURE`

### Additional context

May be good to do a double check for the `create` and `update` contracts pages to ensure signing requirements are up to date with the implementation of rent.

### Hedera network

mainnet, testnet

### Version

vLatest

### Operating system

Windows

**Comment by theekrystallee** [comment]
The docs page was updated. Closing this issue. Thanks Ed!
