### ISSUE TITLE
Youtube video not available

### ISSUE THREAD

**Issue by Whytehorse** [hiero-ledger/hiero-docs#21]
The video link in the readme file is broken. It say "video not available" when I click on it. Might be set to private, not public.

**Comment by SimiHunjan** [comment]
Hi @Whytehorse. I went through the links on the readme and didn't see a link to a video. Maybe I missed it, can you please post the text in a comment here that has the broken link? The home page is readme page here: https://docs.hedera.com/guides/. Thank you!

**Comment by Whytehorse** [comment]
https://github.com/hashgraph/hedera-docs/tree/master/core-concepts/hashgraph-consensus-algorithms

**Comment by SimiHunjan** [comment]
Thank you, the link is updated: https://docs.hedera.com/guides/core-concepts/hashgraph-consensus-algorithms.
