### ISSUE TITLE
Add docs hbar digits between API responses

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#216]
Web3 EVM developers are used to having 18 decimal places for the native currency of the network. It won’t be a deal-breaker for developers if the decimal places are not 18, however, in the Hedera network, it is not simply the case that decimal places are 8. The answer to the question “how many decimal places are there in HBARs” is “it depends” and that's the problem.

HAPI (Crypto + SCS Service (`msg.value`)) → 8 decimals

JSON RPC Relay (passed as arguments) → 8 decimals

Hedera SCS (EVM) → 8 decimals

JSON RPC Relay (`msg.value`) → 18 decimals

As a side effect of this, `gasPrice` uses `18` decimal places since it is utilised only from the JSON RPC Relay

**Comment by theekrystallee** [comment]
Added HBAR decimal place documentation.
