### ISSUE TITLE
How to set-up The Graph with Hedera

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#219]
A guide that describes how to set up The Graph with Hedera.

- Follow-up with Smart Contracts team

**Comment by SimiHunjan** [comment]
Example is available in the relay repo

**Comment by SimiHunjan** [comment]
Demo presented and outline provided. Recording available for review.

**Comment by theekrystallee** [comment]
Tutorial is now live: https://docs.hedera.com/hedera/tutorials/smart-contracts/deploy-a-subgraph-using-the-graph-and-json-rpc
