### ISSUE TITLE
Hint typos

### ISSUE THREAD

**Issue by Whytehorse** [hiero-ledger/hiero-docs#22]
saw a couple of these:
{% hint style="info" %} Hedera Token Service is now live on our networks. Learn more in the blog series, Get started with the Hedera Token Service. Hedera Token Service API information can be found in the SDK section here. {% endhint %}

**Comment by SimiHunjan** [comment]
Hi @Whytehorse. Did you see the "{% hint style="info" %}" in the repo? We use GitBook as our docs platform and I believe some of the formatting from GitBook pages that translate to the repo do not format correctly.

**Comment by Whytehorse** [comment]
Yeah that's probably what's going on.

**Comment by SimiHunjan** [comment]
Thank you, will close the issue.
