### ISSUE TITLE
Unicode ZWSP (zero-width space) put on clipboard with code snippet

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-docs#253]
### Description

Found a code snippet in an example (e.g., here https://docs.hedera.com/hedera/getting-started/create-an-account, the "Import Modules" section). Clicked the little overlapped rectangles to copy it to the clipboard.  Went to an open IntelliJ editor window and pasted it in, found the following:

![image](https://user-images.githubusercontent.com/117694041/214162279-51042bee-ae2f-43b9-9ed5-148195c141fc.png)

That "ZWSP" unicode character in there _shouldn't be_.  Causes a build error too:

![image](https://user-images.githubusercontent.com/117694041/214163046-59e615f3-0e47-4770-bf6f-c34c5bb3d670.png)

(This is MacOS 12.6.1, IntelliJ 2022.3.1 build #IU-223.8214.52)

### Steps to reproduce

As described above.

### Hedera network

other

### Version

v2.19.0

### Operating system

macOS

**Comment by david-bakin-sl** [comment]
Don't know whether it is just this one code snippet, or more.

**Comment by SimiHunjan** [comment]
Thanks for flagging this. Will open up an issue with GitBook to see how to resolve this as it seems it is present in other code snippets.

**Comment by theekrystallee** [comment]
Emailed GitBook on 3/9/23 regarding this issue. Waiting to hear back from the support team.

**Comment by theekrystallee** [comment]
Removed the blank unicode character from the code snippet to fix this issue. 

From GitBook:

> I noticed in the specific code block in your example that there is indeed a blank unicode character. However, I wasn't able to find other instances of this issue.
> Given that, I'm thinking this was a small mistake in copying content into GitBook that copied a blank character in the middle. It should be as simple as removing that character from that specific code block - erasing it and adding the empty line again - and this won't continue to happen.
