### ISSUE TITLE
Links to headers in More Tutorials section are not working

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#262]
### Description

@theekrystallee - The tiles at the top of the page that link to headers are not working as expected after the release of the new layout:

### Steps to reproduce

1. https://docs.hedera.com/hedera/tutorials/more-tutorials
2. Click on a tile
3. Should take to the respective subsection header, but it doesn't

### Hedera network

other

### Version

V1.3

### Operating system

Windows

**Comment by theekrystallee** [comment]
Thanks for catching this @ed-marquez! Fixed bug and merged changes.
