### ISSUE TITLE
Update Text Around Funding for auto-created accounts

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#275]
### Description

Update text in the [Accounts page](https://docs.hedera.com/hedera/core-concepts/accounts) that speaks to funding an auto-created account comes from that new accounts initial balance.
![image](https://user-images.githubusercontent.com/18725916/218893987-830d3445-4133-4460-b0e3-e9658d663672.png)
After[ HIP-542](https://hips.hedera.com/hip/hip-542), when utilizing auto-create flow, the account creation fee is no longer deducted from the account's initial balance. The fee is now paid by the account that is paying for the TransferTransaction.

### Steps to reproduce

Visit https://hips.hedera.com/hip/hip-542 for more information

### Hedera network

mainnet, testnet, previewnet

### Version

2.19.2

### Operating system

macOS

**Comment by SimiHunjan** [comment]
Thank you @a-ridley! Fixed!
