### ISSUE TITLE
Add guide about private topics to the "tutorials" section for the consensus service

### ISSUE THREAD

**Issue by michielmulders** [hiero-ledger/hiero-docs#287]
The consensus service is missing a guide that explains how to send messages to a private topic and how to create such a topic.
@theekrystallee would you mind reviewing change request **#2055 Submit Message to Private Topic**? Thanks!

**Comment by theekrystallee** [comment]
Reviewed! It looks good to merge. Thanks for working on this!

**Comment by michielmulders** [comment]
Merged
