### ISSUE TITLE
Example Updates: Create and Transfer an NFT using a Solidity Contract

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#293]
### Description

@theekrystallee 
This tutorial needs to be updated as some community members reported being unable to run it as is: https://docs.hedera.com/hedera/tutorials/token/create-and-transfer-an-nft-using-a-solidity-contract

**Solution**
here's a repo with the JS updates (https://github.com/ed-marquez/hedera-example-create-nft-solidity). The changes for Java and Go should be the same as JS - I'm including the updated lines for convenience.
If you want to quickly run the repo, [here's a GitPod](https://gitpod.io/#https://github.com/ed-marquez/hedera-example-create-nft-solidity/) (just add a .env with credentials and run node index.js) 

Here are the files/lines that were updated: 

**- Bytecode**
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/binaries/NFTCreator_sol_NFTCreator.bin#L1

**- All lines that set a gas limit or payable amount:**
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/index.js#L40
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/index.js#L51
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/index.js#L52
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/index.js#L72
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/index.js#L88
- Token parameters (to match what precompiles expect)
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/index.js#L59
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/0d4f19a2e78cff83845a0763719cb965efe25b27/index.js#L60

**- Also updated the comments in the NFTCreator.sol contract for clarity.**
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/2d5308b5c377c61978b6a351a109a0f23c978f0c/NFTCreator.sol#L21
- https://github.com/ed-marquez/hedera-example-create-nft-solidity/blob/2d5308b5c377c61978b6a351a109a0f23c978f0c/NFTCreator.sol#L33

### Steps to reproduce

See GitPod setup above.

### Hedera network

mainnet, testnet, previewnet

### Version

v0.35

### Operating system

Windows

**Comment by theekrystallee** [comment]
Thank you for creating this issue! Updated the code in all supported languages (JavaScript, Java, and Go) to ensure the gas limit and payable amount are set to the correct value.
