### ISSUE TITLE
Max transaction fee missing in documentation

### ISSUE THREAD

**Issue by orbis86** [hiero-ledger/hiero-docs#298]
### Description

When minting a new token, quite often the transaction fees exceed the default max transaction fee (especially when Hbar is under 10 cents). Can we please update the code to include a commented out function call to setMaxTransactionFee? It is included in the documentation to update a smart contract but not in the documentation for minting a token.

https://docs.hedera.com/hedera/sdks-and-apis/sdks/tokens/mint-a-token
https://docs.hedera.com/hedera/tutorials/token/create-and-transfer-your-first-nft

### Steps to reproduce

Please check the links
https://docs.hedera.com/hedera/tutorials/token/create-and-transfer-your-first-nft
https://docs.hedera.com/hedera/sdks-and-apis/sdks/tokens/mint-a-token

### Hedera network

mainnet, testnet

### Version

latest

### Operating system

None

**Comment by theekrystallee** [comment]
The docs have been updated.
