### ISSUE TITLE
Documenting token association behavior with Lazy Account Creation

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#299]
### Problem

- Sending HBAR and HTS tokens to an EVM address (for account id that **doesn't** exist yet) results in the creation of a new Hedera account and the transfer is successful - see [this account and the tx](https://hashscan.io/testnet/account/0.0.3980194?app=false&pt=1&ph=1&p2=1)

- Sending HTS tokens to an EVM address (for an account id that **does** exist) errors out saying that the account and token are not associated

![image](https://user-images.githubusercontent.com/72571340/229618125-d4d64d8f-5363-4f78-8525-5b51f481bea6.png)
For context, in that example ^ I sent 10 units of MMT to an EVM address that didn't have an account id yet.
Once the tokens were sent, the account was created ok. 

**So if the account id doesn't exist, the token association is "skipped". 
If the account id does exist the token association is required.**

This came from an internal chat. The participants wanted to flag this change in behavior for HTS token associations to ensure it's included in docs.

@theekrystallee @SimiHunjan 

### Solution

**So if the account id doesn't exist, the token association is "skipped". 
If the account id does exist the token association is required.**

**Comment by theekrystallee** [comment]
The token association behavior with lazy account creation has been documented on the following page:
- Core Concepts: [Auto Account Creation](https://docs.hedera.com/hedera/core-concepts/accounts/auto-account-creation#2.-deposit-tokens-to-the-account-alias-account-id)

Should the behavior be documented on the below page as well?:
- SDK/Token Service: [Associate tokens to an account](https://docs.hedera.com/hedera/sdks-and-apis/sdks/tokens/associate-tokens-to-an-account)

@ed-marquez

**Comment by theekrystallee** [comment]
Documented token association behavior with lazy account creation.
