### ISSUE TITLE
Wording could be improved for 'Custom Token Fees'

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-docs#300]
### Description

w.r.t. [Custom token fees](https://docs.hedera.com/hedera/sdks-and-apis/sdks/tokens/custom-token-fees)

* [This paragraph](https://github.com/hashgraph/hedera-docs/blob/c70fab43f66b78fcb0374e9acff75c9cf362143e/sdks-and-apis/sdks/tokens/custom-token-fees.md?plain=1#L5) - I don't get it at all.
   > All fee collectors can be exempt from being charged custom fees. To exempt all fee collectors from being charged a custom fee you must set all custom fee collectors from being exempt when creating the custom fees ([HIP-573](https://hips.hedera.com/hip/hip-573)). If this is not enabled then custom fees are only exempt for a fee collector account for which it is the collector.

    For one thing it introduces the terms "fee collector account", "account for which it is collector", and "being exempt" just inline, expecting the reader to pick all of that up at once.  And it is confusing wording too.  E.g. "... for a fee collector account for which it is the collector" - what is the "it" referring to?

    * I suggest _defining_ the terms "fee collector account" and, if necessary, "account for which it is the collector".

    And it is just confusing (to me) without such definition which fees the "fee collector" is subject to anyway.  As a wild guess ... it is fees which would be charged if the "fee collector account" is the sender ... or receiver ... of some token transfer - unless it is the treasury account which is exempt anyway the second bullet point under "Limits".

  And it is probably in the wrong place, perhaps it should go in the section "Token Custom Fee Payment". 

* Speaking of which, perhaps the section "Token Custom Fee Payment' should be titled "Custom Token Fee Payment" to match the page title?  Otherwise the reader may wonder, "what's different?"

* [Here](https://github.com/hashgraph/hedera-docs/blob/master/sdks-and-apis/sdks/tokens/custom-token-fees.md?plain=1#L9) it _defines_ a "royalty fee is a fractional fee" but later in this paragraph we learn that a royalty fee is applicable to NFTs only, where in the preceding paragraph where "fractional fee" is defined we learned a fractional fee is applicable to fungible tokens only.  So it doesn't seem like a royalty fee is a fractional fee after all.  Maybe there's some kind of thing _that needs a name_ that both a fractional fee and royalty fee are the two examples of?

    > * A **royalty fee** is a fractional fee ... Applicable to non-fungible tokens only.

    > * A **fractional fee** ... Applicable to fungible tokens only.

* That same section on royalty fee also defines "fallback fee" - though it is not in boldface type to indicate a definition.  That also talks about "to charge the receiving account" though that is the only place in this section that talks about _which_ account, sender or receiver, gets charged - that discussion for all other fees is in the next section.

* Speaking of which, perhaps the section "Token Custom Fee Payment" should be titled "Who Pays The Custom Token Fees?" - and stuff _not_ related to that should be pulled out to a separate section.

* [Here](https://github.com/hashgraph/hedera-docs/blob/c70fab43f66b78fcb0374e9acff75c9cf362143e/sdks-and-apis/sdks/tokens/custom-token-fees.md?plain=1#L13) reference is made to a field `net_of_transfer` which appears nowhere else on this page.  Perhaps it is referring to the `setAssessmentMethod()` taking a `FeeAssessmentMethod` defined below [here](https://github.com/hashgraph/hedera-docs/blob/c70fab43f66b78fcb0374e9acff75c9cf362143e/sdks-and-apis/sdks/tokens/custom-token-fees.md?plain=1#L123)?
    > * Fractional fees ... If the `net_of_transfers` field is set to true, ...'

    > | `setAssessmentMethod(<assessmentMethod>)`             | FeeAssessmentMethod                            | Optional    |

    * by the way, the values of the enum `FeeAssessmentMethod` should be provided here as they help tell the reader what is going on with this method

* [Here](https://github.com/hashgraph/hedera-docs/blob/c70fab43f66b78fcb0374e9acff75c9cf362143e/sdks-and-apis/sdks/tokens/custom-token-fees.md?plain=1#L15) it says:
    > Royalty fees are paid by the account exchanging the fungible value. When the NFT sender does not receive any fungible value, the fallback fee is charged to the NFT receiver

    Which makes it sound like there are three accounts involved here, - the account _exchanging_ the value, the _sender_, and the _receiver_ - and the fee will be charged to either the _exchanger_ or the _receiver_ depending on circumstances (and the _sender_ doesn't get charged the fee at all).  Is this the case?  (What if the account _exchanging_ the tokens is a smart contract, as mentioned in the second bullet point below?)
* [Here](https://github.com/hashgraph/hedera-docs/blob/master/sdks-and-apis/sdks/tokens/custom-token-fees.md?plain=1#L16) we see that there are "native royalty fees" but there's no discussion anywhere of non-native (foreign?) royalty fees.  This line is followed by 3 sub-bullet points - but it looks like the first three are actually _one_ bullet point with three paragraphs and should be formatted that way.  Is that the case?
    >   * Users must understand that native royalty fees are _strictly_ a convenience feature and that the network cannot enforce inescapable royalties on the exchange of a non-fractional NFT.
    * Also the terminology "network cannot possibly intervene" is sort of understandable as "so the network can't always recognize a situation where a royalty fee should be charged" but "cannot possibly intervene" is a bit strange ...  In fact, maybe it should just say _explicitly) something about the exchange must be done in a single `CryptoTransfer` or else none of this stuff about custom fees applies at all.
      >   * For example, if the counterparties agree to split their value transfer and NFT exchange into separate transactions, the network cannot possibly intervene.

* Somewhere near there (link not provided, sorry) it says:
    > The NFT sender and receiver should both sign a single CryptoTransfer
    
    Unfortunately the use of the word "should" instead of "must" is misleading.  In fact it is "must" (I'm pretty sure: Editor needs to check.)  (In fact in all these docs the word "should" should be checked to see if it a "must".)

* [Here](https://github.com/hashgraph/hedera-docs/blob/master/sdks-and-apis/sdks/tokens/custom-token-fees.md?plain=1#L20) isn't that saying the same thing as the non-bulleted point below?

    > * The accounts transferring the token to the receiving accounts are responsible for paying the transfer transaction fee in HBAR.
    >
    > In addition to the custom token fee payment, the sender account is required to pay for the token transfer transaction fee in HBAR.

### Steps to reproduce

1. Go to the ["Custom Token Fees" page](https://docs.hedera.com/hedera/sdks-and-apis/sdks/tokens/custom-token-fees).
2. Read the page while taking in the items mentioned above
3. Can you understand it better than I did?

### Hedera network

other

### Version

Current

### Operating system

None

**Comment by theekrystallee** [comment]
Resolved in [9f78f60](https://github.com/hashgraph/hedera-docs/commit/9f78f6066b78d55bbb2c9c99f9b0ba1b3a745770)
