### ISSUE TITLE
Update State and History Page Narrative for Improved Clarity

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#318]
### Description

The current State and History page is located here: https://docs.hedera.com/hedera/core-concepts/state-and-history
and is difficult to digest and understand clearly. 
There are certain sections that would benefit from formatting, for example this section:
![image](https://user-images.githubusercontent.com/18725916/234120207-cfd253b6-f0a6-4272-b8b8-7a4905f07858.png)

I am suggesting the following changes:

- Re-writing unclear sections of the text, formatting and adding sub-headers
- Adding images/graphics to support the text & core takeaways of the page

### Steps to reproduce

Please see the above description of the issue.

### Hedera network

other

### Version

current

### Operating system

macOS

**Comment by theekrystallee** [comment]
Resolved in [df3ba4a](https://github.com/hashgraph/hedera-docs/commit/df3ba4afc173d76a249fc1da3bc38cc120b93e4b)
