### ISSUE TITLE
Discord reports that the invite is invalid

### ISSUE THREAD

**Issue by gfrascadorio** [hiero-ledger/hiero-docs#32]
When using the 'Discord chat' invite on this docs page:
    https://docs.hedera.com/guides/#have-feedback
discord reports: Invalid Invite.  This invite has expired or you might not have permission to join.  

Expected behavior: not that.

**Comment by SimiHunjan** [comment]
Thanks for the note! Link has been updated.

**Comment by dannykansas** [comment]
Found this as a new interested contributor looking to write an SDK for Rust / Python. 

This bug is probably worth reopening as about [eight references](https://github.com/hashgraph/hedera-docs/search?q=discordapp.com%2Finvite%2FFFb9YFX&type=code) are again showing as invalid.

**Comment by SimiHunjan** [comment]
Hi @dannykansas! Thanks for flagging. I believe all of them are taken care of now.

https://github.com/hashgraph/hedera-docs/search?q=https%3A%2F%2Fdiscord.com%2Finvite%2FFFb9YFX

**Comment by rogeriob2br** [comment]
Hello,
Either the link is broken again, or there is some verification step.
![evidenceng](https://user-images.githubusercontent.com/25432584/135362245-c0341415-f85b-41c5-9a06-44f07acc39ea.png)

**Comment by SimiHunjan** [comment]
@rogeriob2br we had some issues with Discord in the last 48 hours that now should be resolved. Can you please try again and let me know if there are still issues?

**Comment by rogeriob2br** [comment]
Hi @SimiHunjan !
I tried again and it worked normally.
