### ISSUE TITLE
Add "how to suggest a sample application" directly to contributing guide also

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-docs#336]
### Problem

The [docs page for demo applications](https://docs.hedera.com/hedera/tutorials/demo-applications) invites contributions (or suggestions) and points to the contributing guide - but the contributing guide itself doesn't mention this possibility.  Perhaps it should.  (Some people might get there first. I did, for example.)

<img width="826" alt="image" src="https://github.com/hashgraph/hedera-docs/assets/117694041/4b9531ea-ebc8-4d88-a83f-b46903737a99">

Actually, it might be good to cover a few more things w.r.t. contributed demos, e.g., what licenses are acceptable.

### Solution

Update the contributions guide in the obvious way.

**Comment by theekrystallee** [comment]
Thanks for creating this issue @david-bakin-sl 

Updated contributing guide to include how to submit a demo application

<img width="774" alt="Screenshot 2023-05-18 at 11 48 34 AM" src="https://github.com/hashgraph/hedera-docs/assets/56278409/d629e85c-5568-4b21-83bf-8275684bf1e1">
