### ISSUE TITLE
Provide users public and private key when creating new accounts

### ISSUE THREAD

**Issue by Reccetech** [hiero-ledger/hiero-docs#341]
### Problem

We have many tutorials that require users to create new accounts with the private key. For example the token tutorials require that the user first creates a Treasuring account and an account for Alice to demonstrate the functionality. However our Account Creation getting started guide only provides the account ID and the account balance - but does not give the user their new public or private key as needed for the tutorials.

### Solution

Add console outputs to the account creation getting started demo to provide the user the public and private key for the newly created account. For example:
``console.clear();
require("dotenv").config();

const {
	Client,
	PrivateKey,
	AccountCreateTransaction,
	AccountBalanceQuery,
	Hbar,
  } = require("@hashgraph/sdk");
  
  async function environmentSetup() {
	// Grab your Hedera testnet account ID and private key from your .env file
	const myAccountId = process.env.OPERATOR_ID;
	const myPrivateKey = process.env.OPERATOR_PVKEY;
  
	// If we weren't able to grab it, we should throw a new error
	if (myAccountId == null || myPrivateKey == null) {
	  throw new Error(
		"Environment variables myAccountId and myPrivateKey must be present"
	  );
	}
  
	// Create your connection to the Hedera Network
	const client = Client.forTestnet();
	client.setOperator(myAccountId, myPrivateKey);
  
	//Set the default maximum transaction fee (in Hbar)
	client.setDefaultMaxTransactionFee(new Hbar(100));
  
	//Set the maximum payment for queries (in Hbar)
	client.setMaxQueryPayment(new Hbar(50));
  
	// Create new keys
	const newAccountPrivateKey = PrivateKey.generateED25519();
	const newAccountPublicKey = newAccountPrivateKey.publicKey;
  
	// Create a new account with 1,000 tinybar starting balance
	const newAccount = await new AccountCreateTransaction()
	  .setKey(newAccountPublicKey)
	  .setInitialBalance(Hbar.fromTinybars(1000))
	  .execute(client);
  
	// Get the new account ID
	const getReceipt = await newAccount.getReceipt(client);
	const newAccountId = getReceipt.accountId;
  
	console.log("The new account ID is: " + newAccountId);
	**console.log("The new account private key is: " + newAccountPrivateKey);
	console.log("The new account public key is: " + newAccountPublicKey);**
  
	// Verify the account balance
	const accountBalance = await new AccountBalanceQuery()
	  .setAccountId(newAccountId)
	  .execute(client);
  
	console.log(
	  "The new account balance is: " +
		accountBalance.hbars.toTinybars() +
		" tinybar."
	);
  }
  environmentSetup();``

**Comment by theekrystallee** [comment]
Thanks for creating this issue! Code samples have been updated <img width="531" alt="Screenshot 2023-05-31 at 7 09 50 AM" src="https://github.com/hashgraph/hedera-docs/assets/56278409/639af49e-61e9-4f91-86b6-e3f9b99107e3">
