### ISSUE TITLE
Update HCS description

### ISSUE THREAD

**Issue by nickpoorman** [hiero-ledger/hiero-docs#349]
### Description

https://docs.hedera.com/hedera/sdks-and-apis/hedera-consensus-service-api-1
> The Hedera Consensus Service (HCS) gRPC API is a public mirror node managed by Hedera.

I'm not sure that makes sense. HCS is not a public mirror node; it's a service provided by HAPI and one endpoint on the mirror node gRPC API to stream the HCS messages.

### Steps to reproduce

--

### Hedera network

mainnet, testnet, previewnet

### Version

v0.39

### Operating system

None

**Comment by theekrystallee** [comment]
Updated in 62ce324
