### ISSUE TITLE
Auto Scrolling Issue on Landing Documentation Page

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#352]
### Description

On the landing documentation page, there is an issue with the auto-scrolling behavior of the starter links.
When initially clicking on a starter link, the page correctly scrolls to the desired section.
However, if the user manually scrolls back to the top and clicks on the same starter link again, the page does not scroll to that section. 

See the attached video and the steps to reproduce.

https://github.com/hashgraph/hedera-docs/assets/18725916/158e5be2-c839-40a0-a255-de7e1966c4da

### Steps to reproduce

1. Go to the landing page.
2. Click on  "Environment Setup"
3. The page will auto-scroll to the corresponding section.
4. Scroll back up to the top of the page.
5. Click on the "Environment Setup" link again.
6. Notice that the page does not auto scroll to the desired section, instead staying where it is.

### Hedera network

mainnet, testnet, previewnet

### Version

current version

### Operating system

macOS

**Comment by theekrystallee** [comment]
Update from GitBook support:

> I'm afraid I don't have an update to share yet. We do want to improve how scrolling works with cards. However this might not happen soon. Not because we think this is not important. It's because we are dealing with numerous issues that are equally or more severe, and everyone in engineering is focusing on those currently.

**Comment by theekrystallee** [comment]
Closing as GitBook is aware of this problem
