### ISSUE TITLE
Update tutorial: create-and-transfer-an-nft-using-a-solidity-contract to avoid CONTRACT_REVERT

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#353]
### Description

@theekrystallee 
[This tutorial](https://docs.hedera.com/hedera/tutorials/token/create-and-transfer-an-nft-using-a-solidity-contract) creates a Token with Precompiles. However, a user reported a CONTRACT_REVERT due to data type mismatch between the .sol file and the  .js file. 

**Fix:**
Add the following two lines to section 3 and code check of the tutorial:
- .addInt64(250) // NFT max supply
- .addInt64(7000000) // Expiration: Needs to be between 6999999 and 8000001

That will ensure that what the .js file is passing matches what the .sol file is expecting. See details below:

**Problem:**
- Solidity file expecting int64 for the last two inputs for the function that creates the token:
![image](https://github.com/hashgraph/hedera-docs/assets/72571340/c42e35d7-d00c-47da-a617-cd88b6a8c255)

- Code snippet in section 3 not passing int64:
![image](https://github.com/hashgraph/hedera-docs/assets/72571340/80584b32-e130-4443-8ea6-aa6fbdbabe51)

- Code in the Code Check section not passing int64:
![image](https://github.com/hashgraph/hedera-docs/assets/72571340/61cd6606-7222-4955-a396-4c843f91e561)

### Steps to reproduce

Run the example as is and see contract revert

### Hedera network

testnet

### Version

v2.25

### Operating system

Windows

**Comment by theekrystallee** [comment]
Documentation has been and code sample has been updated in commit [615c7b7](https://github.com/hashgraph/hedera-docs/commit/615c7b76e4ca4f0cfaacaae5da2a0885f0678544)
