### ISSUE TITLE
Update tutorial: create-and-transfer-an-nft-using-a-solidity-contract | Token Association Fails due to security updates

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#354]
### Description

@theekrystallee
[This tutorial](https://docs.hedera.com/hedera/tutorials/token/create-and-transfer-an-nft-using-a-solidity-contract) creates a Token with Precompiles. 

The token association using precompiles fails due to the HSCS security model updates. See:
https://hashscan.io/testnet/transactionsById/0.0.23223-1686173501-145489209

This is caused by the token association in the Solidity contract:
 ```
  function transferNft(
        address token,
        address receiver, 
        int64 serial
    ) external returns(int){

        HederaTokenService.associateToken(receiver, token);
        int response = HederaTokenService.transferNFT(token, address(this), receiver, serial);

        if(response != HederaResponseCodes.SUCCESS){
            revert("Failed to transfer non-fungible token");
        }
```

**Possible Solutions:**
Update the example to perform the token association:
- with auto association during the creation of Alice's account
- using HIP-719 or the SDK

### Steps to reproduce

Run the example

### Hedera network

testnet

### Version

v2.25

### Operating system

Windows

**Comment by ed-marquez** [comment]
The issue is fixed by: 
1. Deleting the line:
`HederaTokenService.associateToken(receiver, token);`
in NFTCreator.sol

2. Adding the line:
`.setMaxAutomaticTokenAssociations(10)`
in the account creator function below: 
```
async function accountCreator(pvKey, iBal) {
		const response = await new AccountCreateTransaction()
			.setInitialBalance(new Hbar(iBal))
			.setKey(pvKey.publicKey)
			.setMaxAutomaticTokenAssociations(10)
			.execute(client);
		const receipt = await response.getReceipt(client);
		return receipt.accountId;
	}
```
3. Given that the association is now handled automatically during account creation, let's add some text explaining token-account associations in section 5 of the tutorial.

**Comment by theekrystallee** [comment]
Documentation has been and code sample has been updated in commit [615c7b7](https://github.com/hashgraph/hedera-docs/commit/615c7b76e4ca4f0cfaacaae5da2a0885f0678544)
