### ISSUE TITLE
Review smart contract London Fork references 

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#366]
### Problem

Mainnet Besu EVM was updated to use the Shanghai. There are points in the documentation that reference items as they relate to the London hard fork that should be updated with the appropriate information for the Shanghai hard fork. 

### Solution

Review the smart contracts section and update London hard fork references to the Shanghai information. Make sure the content is still relevant for the Shanghai hard fork.

**Comment by theekrystallee** [comment]
Resolved with 70b5608
