### ISSUE TITLE
API description for `ConsensusCreateTopic` has `memo` field listed twice

### ISSUE THREAD

**Issue by david-bakin** [hiero-ledger/hiero-docs#368]
### Description

If you look at page [**ConsensusCreateTopic**](https://docs.hedera.com/hedera/sdks-and-apis/hedera-api/consensus/consensuscreatetopic) in the section **ConsensusCreateTopicTransactionBody** you'll see that the `memo` field occurs twice.

### Steps to reproduce

Visual inspection of https://docs.hedera.com/hedera/sdks-and-apis/hedera-api/consensus/consensuscreatetopic will suffice.

### Hedera network

other

### Version

N/A

### Operating system

Windows

**Comment by theekrystallee** [comment]
Resolved in [04be0a6](https://github.com/hashgraph/hedera-docs/commit/04be0a6d67e056f1c494e7b060a4e913556228fb)
