### ISSUE TITLE
Fee page doesn't distinguish Consensus Service "GetTopicMessage" from "GetTopicInfo"

### ISSUE THREAD

**Issue by david-bakin** [hiero-ledger/hiero-docs#369]
### Description

It's not clear whether the same fee applies to both "GetTopicMessage" (API spelling may be different) and "GetTopicInfo" - only 
"ConsensusGetInfo" is listed at https://docs.hedera.com/hedera/networks/mainnet/fees#consensus-service

### Steps to reproduce

Visual inspection of https://docs.hedera.com/hedera/networks/mainnet/fees#consensus-service will suffice.

### Hedera network

other

### Version

N/A

### Operating system

Windows

**Comment by SimiHunjan** [comment]
ConsensusGetInfo should change to ConsensusGetTopicInfo as noted here https://github.com/hashgraph/hedera-protobufs/blob/main/services/consensus_get_topic_info.proto.

The consensus service has a way to get topic info. I am not sure what you mean by get topic message as I don't see a query defined for that in the protobufs. You can subscribe to a a topic using the SDK. The SDK calls a mirror node API to return the stream of messages for the topic you subscribed to.

**Comment by david-bakin-sl** [comment]
It is possible I don't know what I'm talking about.  Perhaps this should be closed?

**Comment by theekrystallee** [comment]
API name updated and resolved in [394cf9a](https://github.com/hashgraph/hedera-docs/commit/394cf9a4b7ba2b52f74252e9ad5d41f18118ecd1)
