### ISSUE TITLE
What is the limit on HCS message length?

### ISSUE THREAD

**Issue by david-bakin** [hiero-ledger/hiero-docs#370]
### Description

At [this page](https://docs.hedera.com/hedera/sdks-and-apis/sdks/consensus-service/submit-a-message) we see a highlighted note that specifies "HCS message size: 1024 bytes".  Where at [this page](https://docs.hedera.com/hedera/sdks-and-apis/hedera-api/consensus/consensussubmitmessage#consensussubmitmessagetransactionbody) - the actual API reference - we see "Max size of the Transaction (including signatures) is 6kB".  

And we don't know what size the signatures are, but unless the signatures add up to 5kB that makes it sound like you can have bigger messages.

The true limit, whatever it is, should be specified in both places.  Additional, in the API reference page (the second one) it would be nice to have a note mentioning what the typical size of the transaction with signature is.

### Steps to reproduce

Visual inspection of above two linked pages will suffice.

### Hedera network

other

### Version

N/A

### Operating system

None

**Comment by theekrystallee** [comment]
Confirmed max HCS  message size is 1024 bytes (1 kb). In comparison, the max size of a transaction (including messages and signatures) is 6 kb.

There isn't a fixed signature size, as it varies by transaction.

Updated docs and resolved in [b19b85a](https://github.com/hashgraph/hedera-docs/commit/b19b85a9a24ec5b33dd18eb88b980bf32c9fa63f)
