### ISSUE TITLE
Concept page for keys doesn't explain different use cases for ECDSA vs ED25519 keys

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-docs#372]
### Description

The page [Keys And Signatures](https://github.com/hashgraph/hedera-docs/blob/master/core-concepts/keys-and-signatures.md) says a key can be either ECDSA or ED25519 (or a smart contract ID) but doesn't say what the different use cases are for the two types or how to choose between them or point to another page somewhere which does.  

This is important because you really need to _choose_: e.g., if you go to the [Portal](https://portal.hedera.com) you see that each key type is associated with a different account - resources (hbar, tokens) aren't _shared_ between those accounts.  And you also see there that the ECDSA key has an associated "EVM address" which the ED25519 key doesn't.  So that too indicates there are different use cases for the different keys.

This information should be described here, or on another "core concept" page.

BTW, the page [Account Properties](https://github.com/hashgraph/hedera-docs/blob/master/core-concepts/accounts/account-properties.md), which refers to _this_ page, says

> Accounts can optionally have more than one key associated with them.

But it also doesn't say what the different keys are, whether they can be different types (ECDSA vs ED25519) or must be the same, or what they're for (except for mentioning multisig).

### Steps to reproduce

Inspect the page(s) linked.

### Hedera network

other

### Version

current (`develop`)

### Operating system

None

**Comment by theekrystallee** [comment]
Updated Keys and Signatures page with use cases for ECDSA vs Ed25519 keys.

Resolved in [6d97f8a](https://github.com/hashgraph/hedera-docs/commit/6d97f8a2c65028689f37fda59e1252294a8305e9)
