### ISSUE TITLE
.gitbook/assets has duplicate names if case-insensitivity is applied

### ISSUE THREAD

**Issue by satwikkansal** [hiero-ledger/hiero-docs#377]
### Description

This is what I get when I clone,

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  '.gitbook/assets/Network-topology (1).jpg'
  '.gitbook/assets/network-topology (1).jpg'
  '.gitbook/assets/Network-topology.jpg'
  '.gitbook/assets/network-topology.jpg'
  '.gitbook/assets/Smart Contracts.png'
  '.gitbook/assets/smart contracts.png'
  '.gitbook/assets/Token Service.png'
  '.gitbook/assets/token service.png'

### Steps to reproduce

Just clone the repo on a osx or windows system. You'll see the git warning.

### Hedera network

previewnet

### Version

irrelevant

### Operating system

None

**Comment by theekrystallee** [comment]
Duplicate issue.
