### ISSUE TITLE
Re-word a sentence in Tutorial that mentions entities will need to pay rent

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#379]
### Description

In the following tutorial: https://docs.hedera.com/hedera/tutorials/token/create-and-transfer-an-nft-using-a-solidity-contract

Step 3 mentions setting an expiration date in seconds because entities on Hedera will need to pay "rent" to persist. The way it's phrased could confuse someone to think rent is currently enabled. 

Re-word to make it clear rent is currently not enabled but in the future entities on Hedera will need to pay rent to persist.

### Steps to reproduce

Go to: https://docs.hedera.com/hedera/tutorials/token/create-and-transfer-an-nft-using-a-solidity-contract
Read step 3

### Hedera network

other

### Version

current

### Operating system

macOS

**Comment by theekrystallee** [comment]
Updated and resolved in [036077b](https://github.com/hashgraph/hedera-docs/commit/036077ba403a649a6c353eb09b708ca311699a70)
