### ISSUE TITLE
`TransactionResponse` has wrong fields

### ISSUE THREAD

**Issue by dikel** [hiero-ledger/hiero-docs#380]
### Description

[`TransactionResponse`](https://docs.hedera.com/hedera/sdks-and-apis/hedera-api/miscellaneous/transactionresponse) has the fields of the Protobuf message instead of the `TransactionResponse` class in the SDKs. [Those](https://hashgraph.github.io/hedera-sdk-java/com/hedera/hashgraph/sdk/TransactionResponse.html) are the correct fields for the Java SDK. I checked and they are the same in JS and Go.

### Steps to reproduce

none

### Hedera network

other

### Version

none

### Operating system

None

**Comment by theekrystallee** [comment]
Resolved in [3a346e3](https://github.com/hashgraph/hedera-docs/commit/3a346e3c36262801d9f24c7ad013c5f534803342)
