### ISSUE TITLE
Remove unmaintained Community Hedera Express.js Start Project

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#384]
### Description

The following starter project: https://github.com/publu/hedera-express-boilerplate, is no longer maintained and points to old versions of the SDK, along with 2019 tutorial on how to get started on Hedera. It also links devs to a site called Composer, which is a broken link. 

There is an existing [Hedera maintained Express.js app](https://github.com/hashgraph/hedera-hcs-chat-js) that is a chat that I believe is sufficient as a Hedera Express.js starter project. It is safe to remove the community-maintained Express.js repo that is referenced in this ticket.

### Steps to reproduce

1. Go to https://github.com/publu/hedera-express-boilerplate
2. Clone the repo
3. cd into the repo directory
4. run npm i
5. run npm run start
7. check out the package.json is using `hash-sdk`

### Hedera network

other

### Version

current

### Operating system

macOS

**Comment by theekrystallee** [comment]
Thanks for creating this issue! Resolved in [1dd87ce](https://github.com/hashgraph/hedera-docs/commit/1dd87ce3cb35c08507f56ed9e6820dc4df1fc893)
