### ISSUE TITLE
Scheduled transaction doc contains a confusing/nonsense sentence

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-docs#388]
### Description

Second paragraph of [this doc](https://github.com/hashgraph/hedera-docs/blob/master/core-concepts/scheduled-transaction.md) reads as follows:

> When a user creates a scheduled transaction, the network creates a scheduled entity. The scheduled entity receives an entity ID just like accounts, tokens, etc called a schedule ID. The schedule ID is used to reference the scheduled transaction that was created. The transaction that is being scheduled is referenced by a scheduled transaction ID. **The scheduled transaction can be referred to as the outer transaction while the scheduled transaction can be referenced as the inner transaction.**

Last sentence is obviously confused.

### Steps to reproduce

1. Read the last sentence of the above quoted paragraph.
2. That's it.

### Hedera network

other

### Version

N/A

### Operating system

None

**Comment by theekrystallee** [comment]
Thanks for catching this @david-bakin-sl ! Resolved in [4ec30fc](https://github.com/hashgraph/hedera-docs/commit/4ec30fc8ed7cd103512f809249c517c14504ca58)
