### ISSUE TITLE
Nuxt-based HCS Chat

### ISSUE THREAD

**Issue by scalemaildev** [hiero-ledger/hiero-docs#39]
### Problem

I made a clone of the HCS express chat program that's built on NuxtJS. It also offers two advantages over the starter one: it uses promises instead of sleep statements, and uses json strings over strings demarcated by the Saturn symbol.

Can it be added to the starter projects list for Javascript?

Check it out here: https://github.com/scalemaildev/hashgraph_nuxt_chat

### Solution

N/A

**Comment by SimiHunjan** [comment]
Hi @scalemaildev !

Thank you for your contribution. Your project was added here: https://docs.hedera.com/guides/resources/starter-projects.
