### ISSUE TITLE
Update pricing on docs.hedera.com for bulk minting NFTs

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#392]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/427
```

**Comment by Ashe-Oro** [comment]
hi, just checking on what the new bulk minting pricing is for the docs (checking to make sure it matches what I'm expecting).

**Comment by SimiHunjan** [comment]
hi @Ashe-Oro ! For now, we are adding all the Monday board items to GitHub for docs. I would review this issue in the Monday board for more details.
