### ISSUE TITLE
Suggest adding a context & objective to the Stablecoin Core Concept Page

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#451]
### Problem

First off! Great job on the launch of the Stablecoin Studio! :clap: 

The stablecoin studio core concept page is in need of further providing context on what a stablecoin is & why it is important. This can help bring further clarity to people who are new to the term. 

### Solution

[The Stablecoin Studio's README on GitHub](https://github.com/hashgraph/stablecoin-studio/tree/main#context) does a great job of providing the necessary context & objective to understand the importance of stablecoins. This can help individuals new to the Stablecoin term further understand the project. It would be great to add a similar paragraph to the docs Stablecoin studio core concept page as it may be seen by many more eyes than the stablecoin studio's Github repository.

**Comment by theekrystallee** [comment]
More context and details have been added. Also expanded on the glossary definition of stablecoin https://docs.hedera.com/hedera/open-source-solutions/stablecoin-studio/core-concepts#introduction
