### ISSUE TITLE
Deprecate ETL page

### ISSUE THREAD

**Issue by Reccetech** [hiero-ledger/hiero-docs#462]
### Problem

I believe we should deprecate: https://github.com/hashgraph/hedera-docs/blob/master/core-concepts/mirror-nodes/hedera-etl.md

We have deprecated the underlying pub-sub service. 

### Solution

Investigate with mirror node team if we should deprecate page.

**Comment by theekrystallee** [comment]
Waiting on the green light from the Mirror Node team to move forward with deprecation.

**Comment by theekrystallee** [comment]
Resolved in [dc87265](https://github.com/hashgraph/hedera-docs/commit/dc87265129713d3a0b04d99926d6a626cd399afc)
