### ISSUE TITLE
Add "Ordinals" to the glossary in a Hedera-related way.

### ISSUE THREAD

**Issue by swirlds-ryan** [hiero-ledger/hiero-docs#466]
### Problem

Wanting to learn about how Ordinals on Bitcoin relates to Hedera

### Solution

A glossary definition for the word "Ordinals" that is informed by how it works on Hedera.

### Alternatives

Confusion?

**Comment by theekrystallee** [comment]
Resolved in [0bbd520](https://github.com/hashgraph/hedera-docs/commit/0bbd520c314bb714d58e7bd6a1a775aedbb7b1d2)
