### ISSUE TITLE
Tutorial: How to deploy a contract with REMIX

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#468]
### Problem

TBD

### Solution

Steps were provided in this issue https://github.com/hashgraph/hedera-sdk-js/issues/1965.

**Comment by SimiHunjan** [comment]
References: https://docs.moonbeam.network/builders/build/eth-api/dev-env/remix/
https://ethereum-blockchain-developer.com/2022-03-deposit-withdrawals/07-injected-web3-provider/

**Comment by theekrystallee** [comment]
Remix tutorial added https://docs.hedera.com/hedera/tutorials/smart-contracts/deploy-a-smart-contract-using-remix
