### ISSUE TITLE
Problem with JS SDK Get File Info code sample

### ISSUE THREAD

**Issue by Reccetech** [hiero-ledger/hiero-docs#472]
### Description

In the code on this page: https://docs.hedera.com/hedera/sdks-and-apis/sdks/file-service/get-file-info

In the method code snippet:
`//Create the query
const query = new FileInfoQuery()
  .setFileId(fileId);

//Sign the query with the client operator private key and submit to a Hedera network
const getInfo = await query.execute(client);

console.log("File info response: " +getInfo);`

The last line of the code snippet doesn't work as a console.log. 
What works is "console.log("File info response: " +JSON.stringify(getInfo));"

### Steps to reproduce

Code snippet does not work

### Hedera network

mainnet

### Version

v1

### Operating system

Windows

**Comment by theekrystallee** [comment]
Both of the code snippets work. The +JSON.stringify just puts the response into a string.
