### ISSUE TITLE
Outdated information regarding mirror node rate limits

### ISSUE THREAD

**Issue by pathornteng** [hiero-ledger/hiero-docs#483]
### Description

The information about our public mirror node's rate limit is outdated. 

https://docs.hedera.com/hedera/sdks-and-apis/rest-api

### Steps to reproduce

Based on the discussion with the mirror node team, there are two mirror node clusters that currently support up to 300 RPS. On the top of that, there is also an API cache in front of the mirror that can offload some of the requests and increase the number of RPS that the mirror node can support. We should also mention that this is a global rate limit, not per IP address.

### Hedera network

mainnet, testnet, previewnet, other

### Version

latest

### Operating system

None

**Comment by theekrystallee** [comment]
Resolved in [efd1dba](https://github.com/hashgraph/hedera-docs/commit/efd1dba9719a2b23eb89a85456b21bf4b6068bec)
