### ISSUE TITLE
task: review hello world tutorials

### ISSUE THREAD

**Issue by bguiz** [hiero-ledger/hiero-docs#485]
### Problem

- lack of hello world tutorials

### Solution

- several hello world tutorials will be added, pls review them!
- [discussion](https://swirldslabs.slack.com/archives/C040CSLT7M0/p1698981722710909)

**Comment by theekrystallee** [comment]
@bguiz can this issue be closed or are there more tutorials incoming?

**Comment by theekrystallee** [comment]
Resolves #394
