### ISSUE TITLE
Hedera Service Solidity Libraries: Broken Link

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#491]
### Description

When going to the hedera service solidity Libraries page: https://docs.hedera.com/hedera/sdks-and-apis/sdks/smart-contracts/hedera-service-solidity-libraries and clicking on the TokenCreateContract example to be taken to the github page that holds these examples. Instead, I was given a 404 error.

### Steps to reproduce

1. Visit https://docs.hedera.com/hedera/sdks-and-apis/sdks/smart-contracts/hedera-service-solidity-libraries
2. Scroll down to Header HederaTokenService.sol API docs
3. In the information card click on TokenCreateContract
4. Observe the File Not Found 404 error
![Screenshot 2023-11-07 at 11 11 11 AM](https://github.com/hashgraph/hedera-docs/assets/18725916/042368df-bdc0-44cb-b45e-ea266aea1c4a)

### Hedera network

other

### Version

current

### Operating system

macOS

**Comment by theekrystallee** [comment]
Thanks for catching this. Fixed in [c708ceb](https://github.com/hashgraph/hedera-docs/commit/c708cebc98346dc6b4aff210106165ac4d6a775c)
