### ISSUE TITLE
Reduce the hbar value used in an example or tutorial

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#495]
### Problem

For the purposes of examples and tutorials, we do not need to use large values of hbar. For example, to show a how a TransferTransaction works we can specify one hbar vs 100 hbar. 

### Solution

Review examples and tutorials and if there are places we use over 5 hbar, reduce the value to 5.

**Comment by theekrystallee** [comment]
Resolved in [16d6e6c](https://github.com/hashgraph/hedera-docs/commit/16d6e6c7196e66be24966e4956bfd6130b190ed7)
