### ISSUE TITLE
Add Hashgraph Chess to demo applications

### ISSUE THREAD

**Issue by scalemaildev** [hiero-ledger/hiero-docs#50]
### Problem

I've completed the MVP for Hashgraph Chess, a NuxtJS application that lets users play chess over the HCS testnet. I'd like it added to https://docs.hedera.com/guides/resources/demo-applications as an example project.

### Solution

My repo is: https://github.com/scalemaildev/hashgraph_chess

**Comment by SimiHunjan** [comment]
Thank you @scalemaildev ! Your demo has been added to that section.
