### ISSUE TITLE
Hello World tutorial series feedback/review

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#509]
### Problem

In order to review and merge #507 I needed to set up the project and validate the proposed changes.

The tutorial requires Visual Studio Code 'code' command to be installed globally. I had to follow these instructions to follow the tutorial https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line.

Commands that start with `code` are mentioned throughout the tutorial. We should note that this needs to be enabled in the requirements of this series. It should also be noted that Visual Studio Code is the IDE that this tutorial works alongside side with as the code commands open up the VS Code IDE for the noted files.

If the shell commands were meant to be more for global use i.e. not tied to specific IDE then we should augment the series to not use `code` commands. 

- [x] Run `create and fund account`
Output:
```
accountId: 0.0.485576
accountBalanceTinybars: 10,000.00000000
accountExplorerUrl: https://hashscan.io/testnet/account/0.0.485576
```
- [x] Run `HFS: Files`
```
fileId: 0.0.5953574
fileCreateTxId: 0.0.485576@1700699346.128690047
txExplorerUrl: https://hashscan.io/testnet/transaction/0.0.485576@1700699346.128690047
localFileContents: Hello future! - Simi

networkFileContents: Hello future! - Simi
```

- [ ] Run `HTS: Fungible Token`
- [ ] Run `HSCS: Smart Contract`

### Solution

- Include VS Code IDE in the requirements as well as enabling `code` globally so it can be used in the terminal

**Comment by SimiHunjan** [comment]
- [x] Run `HFS: Files`

I am following this step here:

```
cd 01-hfs-files-sdk/
```

The last place that I leave off from the previous tutorial was in the `00-create-fund-account`

In this section it mentions to use `cd 01-hfs-files-sdk/`

I understand someone may not complete the previous step and will start at the root of the project to run this specific example, but for those that are following along in order maybe we can add a note that says if you are following along from the previous tutorial you can use this command to switch to the files example:

`cd .. && cd 01-hfs-files-sdk/`

```
fileId: 0.0.5953574
fileCreateTxId: 0.0.485576@1700699346.128690047
txExplorerUrl: https://hashscan.io/testnet/transaction/0.0.485576@1700699346.128690047
localFileContents: Hello future! - Simi

networkFileContents: Hello future! - Simi
```

**Comment by bguiz** [comment]
Simi: Thanks for this - I've addressed these.

They're on the preview repo here: https://github.com/hedera-dev/preview-hedera-docs/pull/9
Preview: https://hedera-dev.gitbook.io/preview-hedera-docs/~/revisions/roCe2eLW3GoQFWdRg61n/tutorials/hello-world/create-fund-account

Note that [PR #507](https://github.com/hashgraph/hedera-docs/pull/507) should be merged first, and then this can follow right after.

**Comment by bguiz** [comment]
Simi: Both #510 and #512 have been merged now, so all OK on my end to close this one

**Comment by SimiHunjan** [comment]
ok closing this issue for now thanks!
