### ISSUE TITLE
Glossary update

### ISSUE THREAD

**Issue by swirlds-ryan** [hiero-ledger/hiero-docs#512]
### Problem

Turing Complete: Confusing as it uses itself to define itself

Bytecode: compiled vs deployed bytecode as they are different 

### Solution

Greater clarity on what Turing Completeness is less directly referencing Turing Completeness  https://docs.hedera.com/hedera/support-and-community/glossary#turing-complete

Expansion on what compiled vs deployed bytecode as they are different https://docs.hedera.com/hedera/support-and-community/glossary#bytecode

**Comment by theekrystallee** [comment]
Resolved in c9d9fe9
