### ISSUE TITLE
Tutorial: How to use API key from the Hedera Portal

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#524]
### Problem

A new feature will be added to the Hedera Portal that will show users an API key they can use

> Feature and Scope
> It would be good if we could make the process of re-creating accounts and querying for account Id after a testnet reset through the portal something that can be machine driven
> 
> Impact:
> Testnet resets have a significant impact on CI/CD pipelines amongst others.
> 
> Whenever testnet is reset, an operator has to manually go to the portal, re-create an account, get the new account id and input that new ID in test scripts/environments.
> 
> It breaks tests, requiring diagnostic, manual intervention, adds delays that could be prevented and is prone to user-error.
> 
> User Stories:
> As a developer, I would like to be able to rely on CI/CD tests to work before and after a testnet reset seamlessly.
> As a developer, I would like to be able to obtain an API key from the portal for my profile.
> As a developer, I would like to be able to call an API on the portal (secured with the API key) which returns the accountId associated with my profile
> As a developer, I would like to be able to call an API on the portal (secured with the API key), if the account doesn’t exist, the API call should create an account and return the API key (maybe an asynchronous process).
> References:
> Rivia/BankSocial and likely many others
> 
> Features:
> Add API Key
> 
> Persisted with the main account on portal and does not get reset when the testnet reset occurs
> 
> API Key Management
> 
> Change API keys
> 
> Display when they log in
> 
> Copy and paste
> 
> API settings in portal
> 
> API call: Get root account IDs on testnet
> 
> First API call kicks off the process of creating the testnet account after a testnet reset
> 
> Get ED25519 Root Account
> 
> Get ECDSA Root Account
> 
> Solution
> Implement the listed features

### Solution

Create a tutorial demonstrating the use of this feature. 

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/553
```

**Comment by theekrystallee** [comment]
Resolved in [2db233a](https://github.com/hashgraph/hedera-docs/commit/2db233a973bb0ab4b407716db3e975f2a0803d4b)
