### ISSUE TITLE
Add  HIP-765: NFT Collection Token Metadata Field docs

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#529]
### Problem

The Hedera consensus node software will be planning to release this feature in an upcoming release.

Update documentation to include information for HIP-765

[HIP-765:](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-765.md) NFT Collection Token Metadata Field

### Solution

Update documentation

**Comment by theekrystallee** [comment]
Resolved in [5c87ca5](https://github.com/hashgraph/hedera-docs/commit/5c87ca58987f7fd0af56e7737fc661bb69543e53)
