### ISSUE TITLE
Adding MetaMask Snaps How-to Tutorial 

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#534]
### Problem

Regarding the how-to article I'm writing for MetaMask Snaps, the content is a better fit for our documentation than the blog. It's fairly detailed and longer than a typical blog, so GitBook has better tools to make it more digestible.
I'll finish writing up with week and create a draft/PR on GitBook for us to iterate on this week.

### Solution

- [here's a sample dapp](https://gitpod.io/#https://github.com/ed-marquez/hedera-example-metamask-snap) (screenshot attached too - img 1) that I'll use for the how-to article that will be available as a resource for developers.
- You can try the sample dapp by clicking the GitPod link. Once the short setup is complete, you should be able to click "Open Browser" in the lower right corner (see img 2)

**Process:**
The dapp, and subsequent article, show the following steps:

1. Pair MetaMask wallet (select network and account)
2. Install the Hedera Wallet Snap
3. Get the snap EVM address and send it HBAR to create the corresponding snap account
4. Get the snap account info again to see its balance (and to connect the Hedera Wallet Snap to the MetaMask account - this is done as part of invoking a method for the first time)
5. Call other methods in the Hedera Wallet Snap as desired: getAccountInfo, transferCrypto
6. Display info and/or results in the console and UI

@krs

**Comment by theekrystallee** [comment]
Tutorial added and resolved in [6b241bb](https://github.com/hashgraph/hedera-docs/commit/6b241bb55641f9a1c7c73d979795ffd04519621c)
