### ISSUE TITLE
Verifying Smart Contracts page improvements

### ISSUE THREAD

**Issue by acuarica** [hiero-ledger/hiero-docs#542]
Just some suggestions for the [Verifying Smart Contracts](https://docs.hedera.com/hedera/core-concepts/smart-contracts/verifying-smart-contracts-beta) page

- [x] Reflect that metadata is not part of the EVM. This comes from another issue https://github.com/hashgraph/hedera-sourcify/issues/124. All details are there.
- [x] It might be worth to also add Foundry in the Metadata File section, given it is heavily used in the community.
- [x] And maybe make the subsection _Different Instances of Sourcify[...]_ more prominent. This is because the beginning of the page mentions Sourcify which might confuse the user later on.

**Comment by theekrystallee** [comment]
Resolved in [4fa9bd9](https://github.com/hashgraph/hedera-docs/commit/4fa9bd9d9dc10839abd31e3406f7a558621a89fb)
