### ISSUE TITLE
Add HIP-844 docs

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#543]
### Problem

HIP: https://hips.hedera.com/hip/hip-844

Protobuf PR: https://github.com/hashgraph/hedera-protobufs/pull/312

Introduce rules for when to update an Ethereum transaction signer’s nonce and a new field for externalising the nonce update in the record stream. This will help resolve issues where the Consensus nodes and the Mirror nodes are out of sync in regards to what the current value of an account’s nonce is. 

```jsx
message ContractFunctionResult {
    
    [...]

    /**
     * If not null this field specifies what the value of the signer account nonce is post transaction execution. 
     * For transactions that don't update the signer nonce (like HAPI ContractCall and ContractCreate transactions) this field should be null.
     */
    Int64Value signer_nonce = 15;
}
```

### Solution

Update ContractFunctionResult section https://docs.hedera.com/hedera/sdks-and-apis/sdks/smart-contracts/call-a-smart-contract-function-1

**Comment by theekrystallee** [comment]
Resolved in [ea8e999](https://github.com/hashgraph/hedera-docs/commit/ea8e999bc2f5c85c474e52a8d09afc9f3a879d27)
