### ISSUE TITLE
Update `hedera-local-node` docs

### ISSUE THREAD

**Issue by georgi-l95** [hiero-ledger/hiero-docs#552]
Current hedera-local-node documentations is a little out of date due to the recent updates to the tool itself.

Here're most of the changes, as well as some highlights, which can be taken into account when updating:

- Starting is now done by using `npm run start` instead of `node cli.js start` . Same for `restart`/`stop`/`generate-accounts`
- It's possible to start only using `docker compose up`, but this will not generate the first 30 accounts
- All available commands can be checked out [here](https://github.com/hashgraph/hedera-local-node/tree/main?tab=readme-ov-file#using-hedera-local).
- Multinode mode is now working , we've also added documentation for it, with explanation how to start it and how it's working -> [Docs](https://github.com/hashgraph/hedera-local-node/blob/main/docs/multinode-mode.md)
- You can once against start in detached mode, by just adding `-d`. Example - `npm run start -- -d`
- Detached mode is now more beautiful. It has more information and verbose settings (for now between info and trace).
- We've fixed annoying asking for admin rights, when package is installed globally. (no more sudo🎉)
- Tested and working on Linux, Mac and Windows.

**Comment by theekrystallee** [comment]
Resolved in [9a5f075](https://github.com/hashgraph/hedera-docs/commit/9a5f07516f3861ace06ce9d404be68658bb0c909) and will include updates to the Localnet docs
