### ISSUE TITLE
API Key feature - Small error in instructions for getting accounts by public key

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#553]
### Description

In this page:
https://docs.hedera.com/hedera/~/changes/zixQ3qqrRRbOvGSVdsHR/tutorials/more-tutorials/how-to-create-a-personal-access-token-api-key-on-the-hedera-portal

There's a slight inconsistency. The endpoint helps users get portal accounts with the public key, but the instructions say to use DER ENCODED PRIVATE KEY. Using the public key works well and is a better practice.

### Steps to reproduce

![image](https://github.com/hashgraph/hedera-docs/assets/72571340/12d7753e-28d7-49bd-acf7-93c98e8b8fd8)

### Hedera network

testnet, previewnet

### Version

draft

### Operating system

Windows

**Comment by theekrystallee** [comment]
Thanks for catching this! The draft has been updated 
<img width="739" alt="Screenshot 2024-01-26 at 6 58 30 AM" src="https://github.com/hashgraph/hedera-docs/assets/56278409/2d89abbb-131b-4e75-9572-d13f1e6e5cd5">
