### ISSUE TITLE
docs: mention `stateRoot` in EVM equivalence page

### ISSUE THREAD

**Issue by bguiz** [hiero-ledger/hiero-docs#562]
### Problem

- The `eth_getBlockBy*` RPC requests always return a zero value for `stateRoot`
- This is a variation that has impacts on EVM-comaptibility/equivalence

### Solution

- Update [`/hedera/core-concepts/smart-contracts/hederas-evm-equivalence-goals-and-exceptions`](https://docs.hedera.com/hedera/core-concepts/smart-contracts/hederas-evm-equivalence-goals-and-exceptions) to add mention that `stateRoot` will be always be a zero value for these RPCs

### Alternatives

Refs:

- https://github.com/hashgraph/hedera-json-rpc-relay/issues/1996
- https://github.com/hashgraph/hedera-json-rpc-relay/pull/2061
- https://swirldslabs.slack.com/archives/C03EHC2H8CR/p1706056921483199

**Comment by theekrystallee** [comment]
Resolved in [f0027f2](https://github.com/hashgraph/hedera-docs/commit/f0027f295edc90207ed9509155392c165578b2c6)
