### ISSUE TITLE
Update fees page for `TokenUpdateNftTransaction`

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#569]
### Problem

A new transaction type will be introduced. The fees page will need to add the new transaction type and associated transaction fee. 

### Solution

Update fees page when the transaction fee becomes available.

**Comment by theekrystallee** [comment]
Resolved in [5c87ca5](https://github.com/hashgraph/hedera-docs/commit/5c87ca58987f7fd0af56e7737fc661bb69543e53)
