### ISSUE TITLE
Update Use Cases for Key Types

### ISSUE THREAD

**Issue by may-hashpack** [hiero-ledger/hiero-docs#571]
### Problem

https://docs.hedera.com/hedera/core-concepts/keys-and-signatures

On the Use Cases table for the 'Choosing between ECDSA and Ed25519 Keys' section, the description says "It's your only option for Hedera native wallets like HashPack as they don't support ECDSA keys'.

This is incorrect. HashPack currently fully supports ECDSA keys.

### Solution

Delete the sentence in the table around HashPack not supporting ECDSA.

Optionally, add a line somewhere to educate users that Hedera wallets such as HashPack support both key types.

**Comment by theekrystallee** [comment]
Resolved in [38c2374](https://github.com/hashgraph/hedera-docs/commit/38c23749637d18b0b173fb5f1c3676b3bd8ce6de)
