### ISSUE TITLE
Clarify (new) testnet faucet behavior "information callout"

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-docs#578]
At https://docs.hedera.com/hedera/getting-started/introduction we see:

<img width="842" alt="image" src="https://github.com/hashgraph/hedera-docs/assets/117694041/85fa3ee7-3a9e-4d4d-bdc7-6745d56fbf69">

I found that confusing as the wording "... your balance will be topped up to 1000HBAR every 24-hour period" seems to imply that the balance **will** be topped off **every 24-hour period** - hearkening back to the now-removed _auto_-top-off instead of indicating that you have to press a button each day.  

Also it is a bit odd, to me, that "if you have 500 HBAR in your account" it will be topped off _every_ day.  Instead of just that one time when you have 500 HBAR.  Perhaps the example of 500->1000 should be a separate paragraph (explaining that topping off means you don't get another 1000 HBAR (once a day) when you press the button, you get an account that has at least 1000 HBAR in it.)

**Comment by theekrystallee** [comment]
Updated callout:
> Note: Testnet accounts on the developer portal are subject to a daily top-up limit of 1000 HBAR. Accounts do not automatically get topped up. To maintain your balance, you must manually request a refill through the portal dashboard every 24 hours.
For clarity, topping up does not add 1000 HBAR to your account balance each time you refill. Instead, your account balance is replenished up to 1000 HBAR if it falls below this threshold. For example, if your account balance is 500 HBAR, refilling will only add enough HBAR to bring your balance to 1000 HBAR, not an additional 1000 HBAR. 

Resolved in [7369fda](https://github.com/hashgraph/hedera-docs/commit/7369fda608ec8b9f0f6d0a4f5a2560d5344c1edd)
