### ISSUE TITLE
Add 0.47 release notes to docs 

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#590]
### Problem

When Services publishes the 0.47 release notes here: https://github.com/hashgraph/hedera-services/releases/tag/v0.47.0 add them to the release notes section. 

### Solution

see above

**Comment by theekrystallee** [comment]
Resolved in [02abd66](https://github.com/hashgraph/hedera-docs/commit/02abd66c292dfe51655ef200b64bad05e3a4c757)
