### ISSUE TITLE
Update Hedera Local Node tutorial with additional requirement

### ISSUE THREAD

**Issue by michielmulders** [hiero-ledger/hiero-docs#593]
### Problem

The Hedera Local Node `DockerService` requires a `docker.sock` file to exist within the `/var/run/` folder on a machine. However, this file (symlink) appears not automatically created for all distributions (for example, Mac Apple Silicon chips like M1 or M2). 

Reference issue and solution: https://github.com/hashgraph/hedera-local-node/issues/537 

### Solution

Docker Desktop has included an option which is disabled by default to automatically created this symlink in order for Hedera Local Node to work on your machine. By enabling this setting, the local node runs as expected on your machine.

Therefore, this additional step should be added to the Docker config steps to ensure users have the `docker.sock` file in the right place.

**Comment by michielmulders** [comment]
Preview link: https://github.com/hedera-dev/preview-hedera-docs/pull/22 (see link in CI/CD checks)

**Comment by theekrystallee** [comment]
Resolved in [bcf3795](https://github.com/hashgraph/hedera-docs/commit/bcf37959ae10fce65d8387edd977809e23c9232b)
