### ISSUE TITLE
Response Code page can be improved

### ISSUE THREAD

**Issue by quiet-node** [hiero-ledger/hiero-docs#595]
### Problem

Currently, the Response Code page lists all the response codes in a table, which makes it impossible to point at a specific response code. 

### Solution

Instead of a table, create headings (using `#` symbols) for each response code.

**Comment by theekrystallee** [comment]
Resolved in [eb7b19c](https://github.com/hashgraph/hedera-docs/commit/eb7b19c79549d68745bb6c01851b85b26b7cc414)

https://docs.hedera.com/hedera/sdks-and-apis/hedera-api/miscellaneous/responsecode
