### ISSUE TITLE
Consolidate Oracle Integrations with a Main Page

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#608]
### Problem

Other types of tools, like network explorers, have a "landing page" on docs that points to the different options developers can use. See the [Network Explorers and Tools](https://docs.hedera.com/hedera/networks/community-mirror-nodes) page for an example.

As we onboard new oracle networks in 2024, we should have a similar landing page for oracles.

### Solution

Under [Open Source Solutions and Integrations](https://docs.hedera.com/hedera/open-source-solutions), we should have a landing page named "Oracle Networks", where we should have a tiled view similar to that of network explorers: 
![image](https://github.com/hashgraph/hedera-docs/assets/72571340/3d587657-f3d4-4cc9-893c-273a3cc1849d)

but listing oracle providers like Pyth, Supra, and others later on...

cc: @theekrystallee

**Comment by richardaroy1** [comment]
Absolutely agree...

**Comment by theekrystallee** [comment]
Added and resolved in [dcb481c](https://github.com/hashgraph/hedera-docs/commit/dcb481cdee10037f713ef4911bfca05ee67c9a5b)

https://docs.hedera.com/hedera/open-source-solutions/oracle-networks
