### ISSUE TITLE
add gitpod + hedera-local-node tutorial

### ISSUE THREAD

**Issue by bguiz** [hiero-ledger/hiero-docs#626]
## What

- add tutorial on how to use gitpod with hedera local node

## Why

- `hedera-local-node` has recently added support for gitpod
- users can run a "cloud development environment" instead of a local development environment, saving set up time, and reducing friction for getting started, and easier to do trials

## Refs

- Related: https://github.com/hashgraph/hedera-local-node/pull/563
- Related: https://github.com/hashgraph/hedera-docs/issues/552
- Related: https://github.com/hashgraph/hedera-docs/issues/558

**Comment by theekrystallee** [comment]
Resolved in [e510bd1](https://github.com/hashgraph/hedera-docs/commit/e510bd1db42a976c733429aad5f91d0e2f5514e2)
