### ISSUE TITLE
Include information about the impact of adding keys on transaction fees - e.g: token create with multiple signing keys

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#63]
### Problem

This issue was reported from a user who experienced higher-than-expected network fees when creating and minting NFTs. 

### Solution

The user suggested updating the information in docs, and according to him, "designers do not look at pricing calculator when making design decisions." - Looks like they're more likely to be looking at documentation to guide those decisions.

The user suggests: **include a clause which indicates that "adding a supply key would impact your network charges (see pricing calculator - link)"** It would be good to add a standard text for all other keys that impact costs, not just supply key.

**Comment by SimiHunjan** [comment]
add this information to each transaction and query page:

Transaction Fees
Please see the transaction and query [fees](https://github.com/o/-LuC734MpqlgwA6zyhAO/s/-LsUmP_7NoX2exvbv_Ps/~/changes/SbpJIRdoa7WzNvaE3XnL/mainnet/fees#transaction-and-query-fees) table for base transaction fee
Please use the [Hedera fee estimator](https://hedera.com/fees) to estimate your transaction fee cost

and updated the description here https://docs.hedera.com/guides/mainnet/fees#transaction-and-query-fees
