### ISSUE TITLE
Change mainnet-public URLs to mainnet

### ISSUE THREAD

**Issue by steven-sheehy** [hiero-ledger/hiero-docs#642]
### Problem

`mainnet-public.mirrornode.hedera.com` was used historically but we'd prefer people use the simpler `mainnet.mirrornode.hedera.com` going forward.

### Solution

Please change all `mainnet-public.mirrornode.hedera.com` references to `mainnet.mirrornode.hedera.com`

**Comment by theekrystallee** [comment]
Resolved in [de706ba](https://github.com/hashgraph/hedera-docs/commit/de706ba6ec08530e969f82d490d4c74606ef1ba9)
