### ISSUE TITLE
Improve "Delete an Allowance" docs

### ISSUE THREAD

**Issue by Reccetech** [hiero-ledger/hiero-docs#693]
### Description

Currently the first line in the docs for [Delete an Allowance](https://docs.hedera.com/hedera/sdks-and-apis/sdks/accounts-and-hbar/adjust-an-allowance) says "A transaction called by the token owner to delete allowances **for NFTs only**." This is misleading as this function as explained in the next line can be used to delete HBAR or FT allowances. 
I think a better explanation of this overall function is in the proto docs: https://hashgraph.github.io/hedera-protobufs/#proto.CryptoDeleteAllowanceTransactionBody

Can we edit this text. 

### Steps to reproduce

See above description

### Hedera network

mainnet

### Version

v0.1

### Operating system

Windows

**Comment by theekrystallee** [comment]
Updated and resolved in [c1a8b08](https://github.com/hashgraph/hedera-docs/commit/c1a8b08a4ba4b692c3d0e3988b361e06cd5b513b)
