### ISSUE TITLE
Add information about the new endpoint (/api/v1/accounts/{accountId}/nfts) added in v0.52 

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#70]
### Problem

in [v0.52 of the Mirror Node](https://docs.hedera.com/guides/docs/release-notes/mirror-node#v0.52), we added the endpoint `/api/v1/accounts/{accountId}/nfts`.

This endpoint is not yet documented in https://docs.hedera.com/guides/docs/mirror-node-api/rest-api#accounts-1

### Solution

@SimiHunjan, a user flagged on Discord that we should add information about the new `/api/v1/accounts/{accountId}/nfts` endpoint in https://docs.hedera.com/guides/docs/mirror-node-api/rest-api#accounts-1

**Comment by SimiHunjan** [comment]
thanks for flagging Ed. 

API docs added https://docs.hedera.com/guides/docs/mirror-node-api/rest-api#nfts-by-account-id
