### ISSUE TITLE
Mirror node database size is low

### ISSUE THREAD

**Issue by gregscullard** [hiero-ledger/hiero-docs#708]
### Description

This mirror documentation refers to a database size of 200Gb, as far as I know, mainnet is currently 50Tb and testnet 250Gb or so, should we update the documentation ?

https://docs.hedera.com/hedera/core-concepts/mirror-nodes/run-your-own-beta-mirror-node#persistent-disk-accompanying

### Steps to reproduce

n/a

### Hedera network

other

### Version

n/a

### Operating system

None

**Comment by theekrystallee** [comment]
Resolved in 9fa1acc
