### ISSUE TITLE
Update HIP-869 dynamic address book transaction fees

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#710]
The fees table needs to be updated with the fees for the following transaction types:

- NodeCreate
- NodeUpdate
- NodeDelete

The transaction fee for these transaction types are $0.001.

**Comment by theekrystallee** [comment]
resolved [508755c](https://github.com/hashgraph/hedera-docs/commit/508755c490d83306232465d8d82708221e85378d)
