### ISSUE TITLE
Remove references to stateproof REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hiero-ledger/hiero-docs#722]
### Problem

Leadership has given the go ahead to de-emphasize the `/api/v1/transactions/{id}/stateproof` mirror node REST API. They asked that it be removed from the docs as a first step.

### Solution

Remove references to stateproof API on docs.hedera.com

**Comment by theekrystallee** [comment]
Removed in [8ecf6d2](https://github.com/hashgraph/hedera-docs/commit/8ecf6d27a6414e9282156f14c60265cc64b8c006)
