### ISSUE TITLE
Broken links to example contracts related to HIP 218

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#73]
### Description

@simi-hedera, both links under this section of the page:
https://docs.hedera.com/guides/core-concepts/smart-contracts/supported-erc-token-standards#examples
are broken. 

I believe those links should point to these two examples: 
- https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/resource/contract/contracts/ERC20Contract/ERC20Contract.sol

- https://github.com/hashgraph/hedera-services/blob/master/test-clients/src/main/resource/contract/contracts/ERC721Contract/ERC721Contract.sol

which now live in this path:
https://github.com/hashgraph/hedera-services/tree/master/test-clients/src/main/resource/contract/contracts

### Steps to reproduce

Open https://github.com/hashgraph/hedera-services/tree/master/test-clients/src/main/resource/contract/contracts
Click example contracts linked in that section
Receive 404 error

### Hedera network

other

### Version

v0.25

### Operating system

Windows

**Comment by SimiHunjan** [comment]
Thanks @ed-marquez . Fixed https://docs.hedera.com/guides/core-concepts/smart-contracts/supported-erc-token-standards.
