### ISSUE TITLE
Add QuickNode to the list of JSON RPC providers in the Hedera ecosystem

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#750]
### Problem

it appears QuickNode is now supporting Hedera Testnet and Mainnet. We should add it to the list of providers on our docs pages.

https://x.com/hbar_foundation/status/1816863294247862775?s=46&t=11Y-sYadrUJfPVoGh6w7Aw

https://x.com/quicknode/status/1816855025660137866?s=46&t=11Y-sYadrUJfPVoGh6w7Aw

### Solution

Update: https://docs.hedera.com/hedera/core-concepts/smart-contracts/deploying-smart-contracts/json-rpc-relay

and other places where JSON RPC providers are listed

**Comment by theekrystallee** [comment]
Resolved in [2f61a25](https://github.com/hashgraph/hedera-docs/commit/2f61a2510a5089dd1a7634467aa51225666a8a0d)
