### ISSUE TITLE
Link to Hedera WalletConnect in Open Source Solutions and Integrations

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#772]
### Problem

Some developers still go to wallet-specific connectors, like HashConnect, because they're not aware that Hedera Wallet Connect with the common standard that Hedera native wallets are using in their implementations.

### Solution

Link to Hedera Wallet Connect:
https://github.com/hashgraph/hedera-wallet-connect?tab=readme-ov-file#overview

from the `Open Source Solutions and Integrations` section of the docs:
https://docs.hedera.com/hedera/open-source-solutions

**Comment by theekrystallee** [comment]
Resolved in [27d652f](https://github.com/hashgraph/hedera-docs/commit/27d652f004d8490f9435c51db18a9fcefe57d4fc)
