### ISSUE TITLE
Change URL for `JSON-RPC Relay` tile in EVM-Compatible tools section

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#774]
### Problem

The URL for the `JSON-RPC Relay` tile in the [EVM-Compatible Tools section of the welcome page](https://docs.hedera.com/hedera#evm-compatible-tools),
![image](https://github.com/user-attachments/assets/9ad5737c-1668-48e5-bb8e-847cbb1e5910)
currently points straight to the [GitHub repo of the relay](https://github.com/hashgraph/hedera-json-rpc-relay?tab=readme-ov-file#hedera-json-rpc-relay).

This assumes/implies that people are already familiar with running their own relay, which is likely not the case. 

### Solution

[FIX 1] Let's updated the tile text to: 
> JSON-RPC makes it easy for existing EVM-based libraries, dev tools, and wallets to work effortlessly on Hedera. **Use a community-hosted JSON-RPC relay or run your own**.

[FIX 2] That link should point to https://docs.hedera.com/hedera/core-concepts/smart-contracts/deploying-smart-contracts/json-rpc-relay#community-hosted-json-rpc-relays , which provides more context about the options available for use.

[FIX 3] That section on `Community Hosted JSON-RPC Relays` should include a tile for `Run Your Own Relay`, which should point to the [GitHub repo of the relay](https://github.com/hashgraph/hedera-json-rpc-relay?tab=readme-ov-file#hedera-json-rpc-relay)

**Comment by theekrystallee** [comment]
resolved 2508fff
