### ISSUE TITLE
Node Requirements - Documentation Issue

### ISSUE THREAD

**Issue by mactel-shaun** [hiero-ledger/hiero-docs#784]
### Description

I notice the current documentation for node requirements has the following requirements:

Sequential write sustained:
Minimum: 2,000GB/s
Recommended: 3,000GB/s
Sequential read sustained:
Minimum: 3,000GB/s
Recommended: 4,500GB/s

I can see that prior to #432 they were:

* Sequential read: 6200 MB/s
* Sequential write: 3000 MB/s

Did the unit accidentally switch from MB to GB?

### Steps to reproduce

Refer to https://github.com/hashgraph/hedera-docs/blob/master/networks/mainnet/mainnet-nodes/node-requirements/README.md

### Version

master

### Operating system

None

**Comment by ElijahLynn** [comment]
Looks like your assessment is correct, thank you. I've made a PR to correct this:
* https://github.com/hashgraph/hedera-docs/pull/801
