### ISSUE TITLE
Remove HBAR Faucet Tutorial

### ISSUE THREAD

**Issue by a-ridley** [hiero-ledger/hiero-docs#788]
## Description
This tutorial about creating an HBAR faucet using metamask and react needs to be deprecated/removed. https://docs.hedera.com/hedera/tutorials/smart-contracts/create-an-hbar-faucet-app-using-react-and-metamask

The CRA Hedera dapp template is now integrated with walletconnect and there is a more comprehensive tutorial that showcases metamask and walletconnect that has replaced the HBAR faucet tutorial.
https://docs.hedera.com/hedera/tutorials/more-tutorials/develop-a-hedera-dapp-integrated-with-walletconnect

### Steps to reproduce

This tutorial https://docs.hedera.com/hedera/tutorials/more-tutorials/develop-a-hedera-dapp-integrated-with-walletconnect
replaces this one https://docs.hedera.com/hedera/tutorials/smart-contracts/create-an-hbar-faucet-app-using-react-and-metamask

### Hedera network

testnet

### Version

current

### Operating system

macOS

**Comment by theekrystallee** [comment]
Resolved in 5bc88c6
