### ISSUE TITLE
Update documentation: Add Real World Assets (RWAs) and Payable Token standards

### ISSUE THREAD

**Issue by dougvk** [hiero-ledger/hiero-docs#800]
## Problem

Our documentation needs to be updated to include information about two new token standards:

1. Real World Assets (RWAs)
2. Payable Token

Key points:

- These new standards need to be integrated into our existing documentation structure.
- The new documentation should be placed in the same section where ERC20 and ERC721 standards are currently documented.
- We need to review and understand the existing documentation for these standards:
  - [ERC-3643 Documentation](https://docs.erc3643.org/erc-3643)
  - [ERC-1363 Documentation](https://erc1363.org/)
- The task involves reusing much of the language from these existing ERC documentations and adapting it to fit our current documentation style and structure.
- This update needs to be completed before the end of the year (EOY).

The goal is to ensure our documentation remains up-to-date and comprehensive, including these new token standards alongside the existing ones, while maintaining consistency in language and structure with our current documentation.

### Solution

# Documentation Needed: Real World Assets (RWAs) and Payable Token Standards

## Description
We need to create documentation for two new token standards:
1. Real World Assets (RWAs)
2. Payable Token

These should be inserted into the existing documentation structure, in the same area where ERC20 and ERC721 standards are documented.

## Objective
The goal is to complete this documentation before the end of the year (EOY).

## Resources
- [ERC-3643 Documentation](https://docs.erc3643.org/erc-3643)
- [ERC-1363 Documentation](https://erc1363.org/)

## Tasks
- [ ] Review the ERC documentation links above
- [ ] Re-use much of the language and put it in the part of the docs where ERC20 and ERC721 lives

## Timeline
Deadline: End of Year (EOY)

## Additional Notes
This task is important for keeping our documentation up-to-date with new token standards. Please ensure that the language and structure are consistent with our existing documentation.

**Comment by theekrystallee** [comment]
Resolved in [c2f29d9](https://github.com/hashgraph/hedera-docs/commit/c2f29d93adec2d1a901d9d8ff2a430a7c801e32b)

docs pages
- [ERC-3643](https://docs.hedera.com/hedera/core-concepts/smart-contracts/tokens-managed-by-smart-contracts/erc-3643-real-world-assets-rwa)
- [ERC-1363](https://docs.hedera.com/hedera/core-concepts/smart-contracts/tokens-managed-by-smart-contracts/erc-1363-payable-tokens)
