### ISSUE TITLE
docs enhancement: Hedera EVM versus Ethereum EVM

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#807]
The goal would be to separate differences between the Hedera EVM & Ethereum EVM that are more likely to apply to

1. **Ethereum developers coming to Hedera**: Cross-deploying or migrating. Mainly ECDSA focused. These devs/apps may be limited in their ability to serve existing ecosystem accounts with ED25519 keys (majority today)
2. **Hedera native developers adding smart contract functionality**: ED25519 focused and serving ecosystem accounts with those keys. May need to expand to another chain that only supports ECDSA

@ed-marquez's initial pass at capturing the differences that apply to group **`(1)`** above (**Ethereum developers coming to Hedera**). Please share feedback and thoughts on items that may be in progress, not applicable, or missing.

- No EC recover for ED25519 (coming soon: isAuthorizedRaw/isAuthorized)
- No way to burn HBAR (to be implemented at some point in the future)
- No support for contract snapshots
  - aka. No support for [Fixture functionality in HardHat](https://hardhat.org/tutorial/testing-contracts#reusing-common-test-setups-with-fixtures)
- Signer returned by ECRECOVER after key rotation
- Decimals (8 on Hedera vs 18 on Ethereum)
- `receive()` function does not fire when HBAR is sent to a contract, so you have to create a manual function that’s called instead

**Comment by dougvk** [comment]
Here's another difference I think should be included:

To my understanding, receive() function does not fire when HBAR is sent to a contract, so you have to create a manual function that's called instead

**Comment by theekrystallee** [comment]
Resolved [70ab6ff](https://github.com/hashgraph/hedera-docs/commit/70ab6ff6f8e41133e113456b5c670e0b3e86c085)
