### ISSUE TITLE
Pull "Gas and Fees" Smart Contracts Section Up 1 level

### ISSUE THREAD

**Issue by Nana-EC** [hiero-ledger/hiero-docs#809]
### Problem

Currently the "Gas and Fees" Smart Contracts Section is under "Deploying Smart Contracts".
This makes it hard to find as it's knowledge that should be seen before trying to deploy.

### Solution

Pull "Gas and Fees" Smart Contracts Section Out from under "Deploying Smart Contracts".

Additionally as part of this or in follow up it might be good to pull snippets of the 
- blog post https://hedera.com/blog/pricing-smart-contracts into here if there are useful summaries.
- [system contract gas calc services doc](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/design/services/smart-contract-service/system-contract-gas-calc.md)

**Comment by theekrystallee** [comment]
resolved part 1 in [b463443](https://github.com/hashgraph/hedera-docs/commit/b463443449931af85838baa1daeb74bf9b238a1e)

created follow up for part 2 in #816
