### ISSUE TITLE
Pull "JSON-RPC Relay" out from under "Deploying Smart Contracts" section

### ISSUE THREAD

**Issue by Nana-EC** [hiero-ledger/hiero-docs#810]
### Problem

Currently the "JSON-RPC Relay" Smart Contracts Section is under "Deploying Smart Contracts".
This makes it hard to find as it's knowledge that should be seen before trying to deploy.
Additionally, it's a whole product and similar to the MN REST API in some sense

### Solution

I think a 2 part short-term and long term solution is needed
1. Short Term - Pull "JSON-RPC Relay" Smart Contracts Section Out from under "Deploying Smart Contracts" 1 level
2. Long Term - Make it it's own section similar to Mirror Node, also all the API details similar to MN for easy reference. Inspiration for layouts can be taken for similar products in the EVM ecosystem such as [Alchemy](https://docs.alchemy.com/reference/ethereum-api-endpoints), [Infura](https://docs.infura.io/api/networks/ethereum/json-rpc-methods) etc

**Comment by theekrystallee** [comment]
resolved part 1 in [b463443](https://github.com/hashgraph/hedera-docs/commit/b463443449931af85838baa1daeb74bf9b238a1e)

created follow up for part 2 in #815
