### ISSUE TITLE
Clean up Supra page

### ISSUE THREAD

**Issue by Reccetech** [hiero-ledger/hiero-docs#837]
### Description

On the Supra Oracles page both links to Official Documentation and HBAR price feed are dead.
https://docs.hedera.com/hedera/open-source-solutions/oracle-networks/supra-oracles

In the docs section there is nothing specific on Hedera. I think the best reference in their docs is that Hedera is an Available Network: https://docs.supra.com/oracles/data-feeds/pull-oracle/networks
In terms or price feeds maybe we link to this: https://supra.com/data/details?instrumentName=hbar_usd&providerName=supra

Perhaps on this page we can also link up the Tutorials here:
GitHub Example: [hedera-example-supra-oracle-contract-push](https://github.com/hedera-dev/hedera-example-supra-oracle-contract-push)
GitHub Example: [hedera-example-supra-oracle-contract-pull](https://github.com/hedera-dev/hedera-example-supra-oracle-contract-pull)
In a perfect world these tutorials might be directly on docs.hedera.com

### Steps to reproduce

Docs fix and improvement

### Hedera network

mainnet

### Version

v0.10

### Operating system

Windows

**Comment by Reccetech** [comment]
@ed-marquez Invite your input on the tutorials.

**Comment by theekrystallee** [comment]
resolved in [357603c](https://github.com/hashgraph/hedera-docs/commit/357603c321ce120d73c6cb5a0ce303e67c6798a3)
