### ISSUE TITLE
Change solidity code for 'deploy a contract using HTS' tutorial page

### ISSUE THREAD

**Issue by cisc0f** [hiero-ledger/hiero-docs#85]
### Problem

In the 'Deploy a Contract Using the Hedera Token Service' tutorial page here: [https://docs.hedera.com/guides/getting-started/try-examples/deploy-a-contract-using-the-hedera-token-service](url), there's a variable switch in step 1.

In HTS.sol there's this function:
```
function tokenTransfer(address tokenId, address fromAccountId , address toAccountId , int64 tokenAmount) external {
        int response = HederaTokenService.transferToken(tokenId, toAccountId, fromAccountId, tokenAmount);

        if (response != HederaResponseCodes.SUCCESS) {
            revert ("Transfer Failed");
        }
    }
```

### Solution

The `tokenTransfer` function should be:
```
function tokenTransfer(address tokenId, address fromAccountId , address toAccountId , int64 tokenAmount) external {
        int response = HederaTokenService.transferToken(tokenId, fromAccountId, toAccountId, tokenAmount);

        if (response != HederaResponseCodes.SUCCESS) {
            revert ("Transfer Failed");
        }
    }
```
as docs are saying here: [https://docs.hedera.com/guides/docs/sdks/smart-contracts/hedera-service-solidity-libraries#transfertoken-token-sender-receiver-amount](url)

**Comment by SimiHunjan** [comment]
Thanks @cisc0f fixed!!
