### ISSUE TITLE
Add Repo Maintainers to CODEOWNERS file

### ISSUE THREAD

**Issue by andrewb1269** [hiero-ledger/hiero-docs#850]
# Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Description**:

Update this repositories `.github/CODEOWNER` file to ensure that the repository maintainer
group(s) have full control of the files in this repository.

**Comment by PavelSBorisov** [comment]
No CODEOWNERS file

**Comment by andrewb1269** [comment]
Will not do.
