### ISSUE TITLE
improve threshold/multi-sig docs + examples

### ISSUE THREAD

**Issue by Cooper-Kunz** [hiero-ledger/hiero-docs#9]
Is it possible to add examples for generating threshold/multi-sig keys to [this page](https://docs.hedera.com/guides/docs/sdks/keys) within the SDK docs?

It's also likely worth adding examples for multi-party signing wherever it makes sense.

**Comment by SimiHunjan** [comment]
I have added how to create a key list and threshold key. With the update to v2 docs I will be including a section that will demonstrate how to sign a multisig transaction.

**Comment by SimiHunjan** [comment]
Added example of how to sign and submit a multisig transaction here: https://docs.hedera.com/guides/docs/sdks/transactions/sign-a-multisignature-transaction
