### ISSUE TITLE
For smart contracts need to document limitation of fallback() / receive () functions not executing when contract receives HBAR via crypto transfer

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#90]
### Description

For smart contracts, we need to document a limitation of fallback() / receive() functions that has been reported via Discord by a power user in the DeFi space. The limitation is that fallback() / receive()  functions in a contract do not execute when the contract receives HBAR via crypto transfer. The hbar arrives fine but the msg.sender and msg.value remain null, that's all due to those functions not getting triggered.

Michael T has been involved in chat responses with this user and is aware of the limitation. 

### Steps to reproduce

1. Send HBAR to a contract via crypto transfer
2. See HBAR arrive but fallback() function does not execute code within it

### Hedera network

testnet

### Version

v0.26

### Operating system

Windows

**Comment by SimiHunjan** [comment]
@ed-marquez would it make sense to add this information here https://docs.hedera.com/hedera/core-concepts/smart-contracts/solidity-variables-and-opcodes? It seems this has to do with the solidity opcodes?

**Comment by SimiHunjan** [comment]
adding to this issue #351

**Comment by theekrystallee** [comment]
@ed-marquez following up on this issue. where do you think it makes the most sense for us to publish this documentation? we'd like to add it to our smart contracts section overhaul

**Comment by ed-marquez** [comment]
Thinking here: https://docs.hedera.com/hedera/core-concepts/smart-contracts (if we are planning to have a description for smart contracts the same way we do for Core Concepts => Accounts). Otherwise, here: https://docs.hedera.com/hedera/core-concepts/smart-contracts/solidity-variables-and-opcodes

It may be good to check with Michael T. to place this information in docs in the page that is closest to the reason why the limitation exists.

**Comment by theekrystallee** [comment]
Documented in [45d2ca3](https://github.com/hashgraph/hedera-docs/commit/45d2ca3a20110dd39f6dbc6e1018ff5f974819bd)
